/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CreateAiGame201Response,
  CreateAiGame400Response,
  CreateAiGameMoveRequest,
  CreateAiGameRequest,
  CreateUserRequest,
  GetUser200Response,
} from "../models/index";
import {
  CreateAiGame201ResponseFromJSON,
  CreateAiGame201ResponseToJSON,
  CreateAiGame400ResponseFromJSON,
  CreateAiGame400ResponseToJSON,
  CreateAiGameMoveRequestFromJSON,
  CreateAiGameMoveRequestToJSON,
  CreateAiGameRequestFromJSON,
  CreateAiGameRequestToJSON,
  CreateUserRequestFromJSON,
  CreateUserRequestToJSON,
  GetUser200ResponseFromJSON,
  GetUser200ResponseToJSON,
} from "../models/index";

export interface CreateAiGameOperationRequest {
  createAiGameRequest: CreateAiGameRequest;
}

export interface CreateAiGameMoveOperationRequest {
  gameId: string;
  createAiGameMoveRequest: CreateAiGameMoveRequest;
}

export interface CreateUserOperationRequest {
  userId: string;
  createUserRequest?: CreateUserRequest;
}

export interface DeleteUserRequest {
  userId: string;
}

export interface GetUserRequest {
  userId: string;
}

export interface TimeoutAiGameRequest {
  gameId: string;
}

export interface UpdateUserRequest {
  userId: string;
  createUserRequest: CreateUserRequest;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Create ai game
   */
  async createAiGameRaw(
    requestParameters: CreateAiGameOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateAiGame201Response>> {
    if (requestParameters["createAiGameRequest"] == null) {
      throw new runtime.RequiredError(
        "createAiGameRequest",
        'Required parameter "createAiGameRequest" was null or undefined when calling createAiGame().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/ai-games`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateAiGameRequestToJSON(
          requestParameters["createAiGameRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateAiGame201ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create ai game
   */
  async createAiGame(
    requestParameters: CreateAiGameOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateAiGame201Response> {
    const response = await this.createAiGameRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Create ai game move
   */
  async createAiGameMoveRaw(
    requestParameters: CreateAiGameMoveOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["gameId"] == null) {
      throw new runtime.RequiredError(
        "gameId",
        'Required parameter "gameId" was null or undefined when calling createAiGameMove().',
      );
    }

    if (requestParameters["createAiGameMoveRequest"] == null) {
      throw new runtime.RequiredError(
        "createAiGameMoveRequest",
        'Required parameter "createAiGameMoveRequest" was null or undefined when calling createAiGameMove().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/ai-games/{gameId}/moves`;
    urlPath = urlPath.replace(
      `{${"gameId"}}`,
      encodeURIComponent(String(requestParameters["gameId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateAiGameMoveRequestToJSON(
          requestParameters["createAiGameMoveRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Create ai game move
   */
  async createAiGameMove(
    requestParameters: CreateAiGameMoveOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createAiGameMoveRaw(requestParameters, initOverrides);
  }

  /**
   * Create user
   */
  async createUserRaw(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling createUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/users/{userId}`;
    urlPath = urlPath.replace(
      `{${"userId"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateUserRequestToJSON(requestParameters["createUserRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create user
   */
  async createUser(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.createUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete user
   */
  async deleteUserRaw(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling deleteUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/users/{userId}`;
    urlPath = urlPath.replace(
      `{${"userId"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete user
   */
  async deleteUser(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteUserRaw(requestParameters, initOverrides);
  }

  /**
   * Get user
   */
  async getUserRaw(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/users/{userId}`;
    urlPath = urlPath.replace(
      `{${"userId"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get user
   */
  async getUser(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.getUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Timeout ai game
   */
  async timeoutAiGameRaw(
    requestParameters: TimeoutAiGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["gameId"] == null) {
      throw new runtime.RequiredError(
        "gameId",
        'Required parameter "gameId" was null or undefined when calling timeoutAiGame().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/ai-games/{gameId}/timeout`;
    urlPath = urlPath.replace(
      `{${"gameId"}}`,
      encodeURIComponent(String(requestParameters["gameId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Timeout ai game
   */
  async timeoutAiGame(
    requestParameters: TimeoutAiGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.timeoutAiGameRaw(requestParameters, initOverrides);
  }

  /**
   * Update user
   */
  async updateUserRaw(
    requestParameters: UpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling updateUser().',
      );
    }

    if (requestParameters["createUserRequest"] == null) {
      throw new runtime.RequiredError(
        "createUserRequest",
        'Required parameter "createUserRequest" was null or undefined when calling updateUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/users/{userId}`;
    urlPath = urlPath.replace(
      `{${"userId"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: CreateUserRequestToJSON(requestParameters["createUserRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Update user
   */
  async updateUser(
    requestParameters: UpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.updateUserRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
