/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AiGame
 */
export interface AiGame {
  /**
   *
   * @type {string}
   * @memberof AiGame
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AiGame
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof AiGame
   */
  difficulty: AiGameDifficultyEnum;
  /**
   *
   * @type {string}
   * @memberof AiGame
   */
  result: AiGameResultEnum | null;
  /**
   *
   * @type {Date}
   * @memberof AiGame
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AiGame
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const AiGameDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type AiGameDifficultyEnum =
  (typeof AiGameDifficultyEnum)[keyof typeof AiGameDifficultyEnum];

/**
 * @export
 */
export const AiGameResultEnum = {
  Win: "win",
  Lose: "lose",
  Cancelled: "cancelled",
} as const;
export type AiGameResultEnum =
  (typeof AiGameResultEnum)[keyof typeof AiGameResultEnum];

/**
 * Check if a given object implements the AiGame interface.
 */
export function instanceOfAiGame(value: object): value is AiGame {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function AiGameFromJSON(json: any): AiGame {
  return AiGameFromJSONTyped(json, false);
}

export function AiGameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AiGame {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    difficulty: json["difficulty"],
    result: json["result"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function AiGameToJSON(json: any): AiGame {
  return AiGameToJSONTyped(json, false);
}

export function AiGameToJSONTyped(
  value?: AiGame | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    difficulty: value["difficulty"],
    result: value["result"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
