/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AiGameMove
 */
export interface AiGameMove {
  /**
   *
   * @type {string}
   * @memberof AiGameMove
   */
  country: string;
  /**
   *
   * @type {string}
   * @memberof AiGameMove
   */
  actor: AiGameMoveActorEnum;
  /**
   *
   * @type {number}
   * @memberof AiGameMove
   */
  createdAt: number;
}

/**
 * @export
 */
export const AiGameMoveActorEnum = {
  Player: "player",
  Ai: "ai",
} as const;
export type AiGameMoveActorEnum =
  (typeof AiGameMoveActorEnum)[keyof typeof AiGameMoveActorEnum];

/**
 * Check if a given object implements the AiGameMove interface.
 */
export function instanceOfAiGameMove(value: object): value is AiGameMove {
  if (!("country" in value) || value["country"] === undefined) return false;
  if (!("actor" in value) || value["actor"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function AiGameMoveFromJSON(json: any): AiGameMove {
  return AiGameMoveFromJSONTyped(json, false);
}

export function AiGameMoveFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AiGameMove {
  if (json == null) {
    return json;
  }
  return {
    country: json["country"],
    actor: json["actor"],
    createdAt: json["createdAt"],
  };
}

export function AiGameMoveToJSON(json: any): AiGameMove {
  return AiGameMoveToJSONTyped(json, false);
}

export function AiGameMoveToJSONTyped(
  value?: AiGameMove | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    country: value["country"],
    actor: value["actor"],
    createdAt: value["createdAt"],
  };
}
