/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAiGame201ResponseMovesValue
 */
export interface CreateAiGame201ResponseMovesValue {
  /**
   *
   * @type {string}
   * @memberof CreateAiGame201ResponseMovesValue
   */
  country: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGame201ResponseMovesValue
   */
  actor: CreateAiGame201ResponseMovesValueActorEnum;
  /**
   *
   * @type {number}
   * @memberof CreateAiGame201ResponseMovesValue
   */
  createdAt: number;
}

/**
 * @export
 */
export const CreateAiGame201ResponseMovesValueActorEnum = {
  Player: "player",
  Ai: "ai",
} as const;
export type CreateAiGame201ResponseMovesValueActorEnum =
  (typeof CreateAiGame201ResponseMovesValueActorEnum)[keyof typeof CreateAiGame201ResponseMovesValueActorEnum];

/**
 * Check if a given object implements the CreateAiGame201ResponseMovesValue interface.
 */
export function instanceOfCreateAiGame201ResponseMovesValue(
  value: object,
): value is CreateAiGame201ResponseMovesValue {
  if (!("country" in value) || value["country"] === undefined) return false;
  if (!("actor" in value) || value["actor"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function CreateAiGame201ResponseMovesValueFromJSON(
  json: any,
): CreateAiGame201ResponseMovesValue {
  return CreateAiGame201ResponseMovesValueFromJSONTyped(json, false);
}

export function CreateAiGame201ResponseMovesValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGame201ResponseMovesValue {
  if (json == null) {
    return json;
  }
  return {
    country: json["country"],
    actor: json["actor"],
    createdAt: json["createdAt"],
  };
}

export function CreateAiGame201ResponseMovesValueToJSON(
  json: any,
): CreateAiGame201ResponseMovesValue {
  return CreateAiGame201ResponseMovesValueToJSONTyped(json, false);
}

export function CreateAiGame201ResponseMovesValueToJSONTyped(
  value?: CreateAiGame201ResponseMovesValue | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    country: value["country"],
    actor: value["actor"],
    createdAt: value["createdAt"],
  };
}
