/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateCurrentUserRequest
 */
export interface CreateCurrentUserRequest {
  /**
   *
   * @type {string}
   * @memberof CreateCurrentUserRequest
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof CreateCurrentUserRequest
   */
  country?: string;
}

/**
 * Check if a given object implements the CreateCurrentUserRequest interface.
 */
export function instanceOfCreateCurrentUserRequest(
  value: object,
): value is CreateCurrentUserRequest {
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  return true;
}

export function CreateCurrentUserRequestFromJSON(
  json: any,
): CreateCurrentUserRequest {
  return CreateCurrentUserRequestFromJSONTyped(json, false);
}

export function CreateCurrentUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCurrentUserRequest {
  if (json == null) {
    return json;
  }
  return {
    displayName: json["displayName"],
    country: json["country"] == null ? undefined : json["country"],
  };
}

export function CreateCurrentUserRequestToJSON(
  json: any,
): CreateCurrentUserRequest {
  return CreateCurrentUserRequestToJSONTyped(json, false);
}

export function CreateCurrentUserRequestToJSONTyped(
  value?: CreateCurrentUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    displayName: value["displayName"],
    country: value["country"],
  };
}
