/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAiGame400Response
 */
export interface CreateAiGame400Response {
  /**
   *
   * @type {string}
   * @memberof CreateAiGame400Response
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGame400Response
   */
  message: string;
}

/**
 * Check if a given object implements the CreateAiGame400Response interface.
 */
export function instanceOfCreateAiGame400Response(
  value: object,
): value is CreateAiGame400Response {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function CreateAiGame400ResponseFromJSON(
  json: any,
): CreateAiGame400Response {
  return CreateAiGame400ResponseFromJSONTyped(json, false);
}

export function CreateAiGame400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGame400Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    message: json["message"],
  };
}

export function CreateAiGame400ResponseToJSON(
  json: any,
): CreateAiGame400Response {
  return CreateAiGame400ResponseToJSONTyped(json, false);
}

export function CreateAiGame400ResponseToJSONTyped(
  value?: CreateAiGame400Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    message: value["message"],
  };
}
