/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAiGame201Response
 */
export interface CreateAiGame201Response {
  /**
   *
   * @type {string}
   * @memberof CreateAiGame201Response
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGame201Response
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGame201Response
   */
  difficulty: CreateAiGame201ResponseDifficultyEnum;
  /**
   *
   * @type {string}
   * @memberof CreateAiGame201Response
   */
  result: CreateAiGame201ResponseResultEnum | null;
  /**
   *
   * @type {Date}
   * @memberof CreateAiGame201Response
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateAiGame201Response
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const CreateAiGame201ResponseDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type CreateAiGame201ResponseDifficultyEnum =
  (typeof CreateAiGame201ResponseDifficultyEnum)[keyof typeof CreateAiGame201ResponseDifficultyEnum];

/**
 * @export
 */
export const CreateAiGame201ResponseResultEnum = {
  Win: "win",
  Lose: "lose",
  Cancelled: "cancelled",
} as const;
export type CreateAiGame201ResponseResultEnum =
  (typeof CreateAiGame201ResponseResultEnum)[keyof typeof CreateAiGame201ResponseResultEnum];

/**
 * Check if a given object implements the CreateAiGame201Response interface.
 */
export function instanceOfCreateAiGame201Response(
  value: object,
): value is CreateAiGame201Response {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function CreateAiGame201ResponseFromJSON(
  json: any,
): CreateAiGame201Response {
  return CreateAiGame201ResponseFromJSONTyped(json, false);
}

export function CreateAiGame201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGame201Response {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    difficulty: json["difficulty"],
    result: json["result"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function CreateAiGame201ResponseToJSON(
  json: any,
): CreateAiGame201Response {
  return CreateAiGame201ResponseToJSONTyped(json, false);
}

export function CreateAiGame201ResponseToJSONTyped(
  value?: CreateAiGame201Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    difficulty: value["difficulty"],
    result: value["result"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
