/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAiGameResponseMove
 */
export interface CreateAiGameResponseMove {
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponseMove
   */
  country: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponseMove
   */
  actor: CreateAiGameResponseMoveActorEnum;
  /**
   *
   * @type {number}
   * @memberof CreateAiGameResponseMove
   */
  createdAt: number;
}

/**
 * @export
 */
export const CreateAiGameResponseMoveActorEnum = {
  Player: "player",
  Ai: "ai",
} as const;
export type CreateAiGameResponseMoveActorEnum =
  (typeof CreateAiGameResponseMoveActorEnum)[keyof typeof CreateAiGameResponseMoveActorEnum];

/**
 * Check if a given object implements the CreateAiGameResponseMove interface.
 */
export function instanceOfCreateAiGameResponseMove(
  value: object,
): value is CreateAiGameResponseMove {
  if (!("country" in value) || value["country"] === undefined) return false;
  if (!("actor" in value) || value["actor"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function CreateAiGameResponseMoveFromJSON(
  json: any,
): CreateAiGameResponseMove {
  return CreateAiGameResponseMoveFromJSONTyped(json, false);
}

export function CreateAiGameResponseMoveFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGameResponseMove {
  if (json == null) {
    return json;
  }
  return {
    country: json["country"],
    actor: json["actor"],
    createdAt: json["createdAt"],
  };
}

export function CreateAiGameResponseMoveToJSON(
  json: any,
): CreateAiGameResponseMove {
  return CreateAiGameResponseMoveToJSONTyped(json, false);
}

export function CreateAiGameResponseMoveToJSONTyped(
  value?: CreateAiGameResponseMove | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    country: value["country"],
    actor: value["actor"],
    createdAt: value["createdAt"],
  };
}
