/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAiGameRequest
 */
export interface CreateAiGameRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAiGameRequest
   */
  difficulty: CreateAiGameRequestDifficultyEnum;
}

/**
 * @export
 */
export const CreateAiGameRequestDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type CreateAiGameRequestDifficultyEnum =
  (typeof CreateAiGameRequestDifficultyEnum)[keyof typeof CreateAiGameRequestDifficultyEnum];

/**
 * Check if a given object implements the CreateAiGameRequest interface.
 */
export function instanceOfCreateAiGameRequest(
  value: object,
): value is CreateAiGameRequest {
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  return true;
}

export function CreateAiGameRequestFromJSON(json: any): CreateAiGameRequest {
  return CreateAiGameRequestFromJSONTyped(json, false);
}

export function CreateAiGameRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGameRequest {
  if (json == null) {
    return json;
  }
  return {
    difficulty: json["difficulty"],
  };
}

export function CreateAiGameRequestToJSON(json: any): CreateAiGameRequest {
  return CreateAiGameRequestToJSONTyped(json, false);
}

export function CreateAiGameRequestToJSONTyped(
  value?: CreateAiGameRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    difficulty: value["difficulty"],
  };
}
