/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateWithFriendsGameMoveRequest
 */
export interface CreateWithFriendsGameMoveRequest {
  /**
   *
   * @type {string}
   * @memberof CreateWithFriendsGameMoveRequest
   */
  countryCode: string;
}

/**
 * Check if a given object implements the CreateWithFriendsGameMoveRequest interface.
 */
export function instanceOfCreateWithFriendsGameMoveRequest(
  value: object,
): value is CreateWithFriendsGameMoveRequest {
  if (!("countryCode" in value) || value["countryCode"] === undefined)
    return false;
  return true;
}

export function CreateWithFriendsGameMoveRequestFromJSON(
  json: any,
): CreateWithFriendsGameMoveRequest {
  return CreateWithFriendsGameMoveRequestFromJSONTyped(json, false);
}

export function CreateWithFriendsGameMoveRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWithFriendsGameMoveRequest {
  if (json == null) {
    return json;
  }
  return {
    countryCode: json["countryCode"],
  };
}

export function CreateWithFriendsGameMoveRequestToJSON(
  json: any,
): CreateWithFriendsGameMoveRequest {
  return CreateWithFriendsGameMoveRequestToJSONTyped(json, false);
}

export function CreateWithFriendsGameMoveRequestToJSONTyped(
  value?: CreateWithFriendsGameMoveRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    countryCode: value["countryCode"],
  };
}
