/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateCurrentUser200Response
 */
export interface CreateCurrentUser200Response {
  /**
   *
   * @type {string}
   * @memberof CreateCurrentUser200Response
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateCurrentUser200Response
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof CreateCurrentUser200Response
   */
  country?: string;
  /**
   *
   * @type {Date}
   * @memberof CreateCurrentUser200Response
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateCurrentUser200Response
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the CreateCurrentUser200Response interface.
 */
export function instanceOfCreateCurrentUser200Response(
  value: object,
): value is CreateCurrentUser200Response {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function CreateCurrentUser200ResponseFromJSON(
  json: any,
): CreateCurrentUser200Response {
  return CreateCurrentUser200ResponseFromJSONTyped(json, false);
}

export function CreateCurrentUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCurrentUser200Response {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"],
    displayName: json["displayName"],
    country: json["country"] == null ? undefined : json["country"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function CreateCurrentUser200ResponseToJSON(
  json: any,
): CreateCurrentUser200Response {
  return CreateCurrentUser200ResponseToJSONTyped(json, false);
}

export function CreateCurrentUser200ResponseToJSONTyped(
  value?: CreateCurrentUser200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    displayName: value["displayName"],
    country: value["country"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
