/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAiGameMoveRequest
 */
export interface CreateAiGameMoveRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAiGameMoveRequest
   */
  countryCode: string;
}

/**
 * Check if a given object implements the CreateAiGameMoveRequest interface.
 */
export function instanceOfCreateAiGameMoveRequest(
  value: object,
): value is CreateAiGameMoveRequest {
  if (!("countryCode" in value) || value["countryCode"] === undefined)
    return false;
  return true;
}

export function CreateAiGameMoveRequestFromJSON(
  json: any,
): CreateAiGameMoveRequest {
  return CreateAiGameMoveRequestFromJSONTyped(json, false);
}

export function CreateAiGameMoveRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGameMoveRequest {
  if (json == null) {
    return json;
  }
  return {
    countryCode: json["countryCode"],
  };
}

export function CreateAiGameMoveRequestToJSON(
  json: any,
): CreateAiGameMoveRequest {
  return CreateAiGameMoveRequestToJSONTyped(json, false);
}

export function CreateAiGameMoveRequestToJSONTyped(
  value?: CreateAiGameMoveRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    countryCode: value["countryCode"],
  };
}
