/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateAiGame201ResponseMovesValue } from "./CreateAiGame201ResponseMovesValue";
import {
  CreateAiGame201ResponseMovesValueFromJSON,
  CreateAiGame201ResponseMovesValueFromJSONTyped,
  CreateAiGame201ResponseMovesValueToJSON,
  CreateAiGame201ResponseMovesValueToJSONTyped,
} from "./CreateAiGame201ResponseMovesValue";

/**
 *
 * @export
 * @interface CreateAiGameResponse
 */
export interface CreateAiGameResponse {
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponse
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponse
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponse
   */
  difficulty: CreateAiGameResponseDifficultyEnum;
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponse
   */
  turn: CreateAiGameResponseTurnEnum;
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponse
   */
  start: string;
  /**
   *
   * @type {string}
   * @memberof CreateAiGameResponse
   */
  country: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateAiGameResponse
   */
  availableMoves: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateAiGameResponse
   */
  usedCountries: Array<string>;
  /**
   *
   * @type {{ [key: string]: CreateAiGame201ResponseMovesValue; }}
   * @memberof CreateAiGameResponse
   */
  moves: { [key: string]: CreateAiGame201ResponseMovesValue };
  /**
   *
   * @type {number}
   * @memberof CreateAiGameResponse
   */
  createdAt: number;
  /**
   *
   * @type {number}
   * @memberof CreateAiGameResponse
   */
  updatedAt: number;
}

/**
 * @export
 */
export const CreateAiGameResponseDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type CreateAiGameResponseDifficultyEnum =
  (typeof CreateAiGameResponseDifficultyEnum)[keyof typeof CreateAiGameResponseDifficultyEnum];

/**
 * @export
 */
export const CreateAiGameResponseTurnEnum = {
  Player: "player",
  Ai: "ai",
} as const;
export type CreateAiGameResponseTurnEnum =
  (typeof CreateAiGameResponseTurnEnum)[keyof typeof CreateAiGameResponseTurnEnum];

/**
 * Check if a given object implements the CreateAiGameResponse interface.
 */
export function instanceOfCreateAiGameResponse(
  value: object,
): value is CreateAiGameResponse {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("turn" in value) || value["turn"] === undefined) return false;
  if (!("start" in value) || value["start"] === undefined) return false;
  if (!("country" in value) || value["country"] === undefined) return false;
  if (!("availableMoves" in value) || value["availableMoves"] === undefined)
    return false;
  if (!("usedCountries" in value) || value["usedCountries"] === undefined)
    return false;
  if (!("moves" in value) || value["moves"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function CreateAiGameResponseFromJSON(json: any): CreateAiGameResponse {
  return CreateAiGameResponseFromJSONTyped(json, false);
}

export function CreateAiGameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAiGameResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    difficulty: json["difficulty"],
    turn: json["turn"],
    start: json["start"],
    country: json["country"],
    availableMoves: json["availableMoves"],
    usedCountries: json["usedCountries"],
    moves: mapValues(json["moves"], CreateAiGame201ResponseMovesValueFromJSON),
    createdAt: json["createdAt"],
    updatedAt: json["updatedAt"],
  };
}

export function CreateAiGameResponseToJSON(json: any): CreateAiGameResponse {
  return CreateAiGameResponseToJSONTyped(json, false);
}

export function CreateAiGameResponseToJSONTyped(
  value?: CreateAiGameResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    difficulty: value["difficulty"],
    turn: value["turn"],
    start: value["start"],
    country: value["country"],
    availableMoves: value["availableMoves"],
    usedCountries: value["usedCountries"],
    moves: mapValues(value["moves"], CreateAiGame201ResponseMovesValueToJSON),
    createdAt: value["createdAt"],
    updatedAt: value["updatedAt"],
  };
}
