/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GetAiGames200ResponseByDifficulty } from "./GetAiGames200ResponseByDifficulty";
import {
  GetAiGames200ResponseByDifficultyFromJSON,
  GetAiGames200ResponseByDifficultyFromJSONTyped,
  GetAiGames200ResponseByDifficultyToJSON,
  GetAiGames200ResponseByDifficultyToJSONTyped,
} from "./GetAiGames200ResponseByDifficulty";
import type { GetAiGames200ResponseRecentGamesInner } from "./GetAiGames200ResponseRecentGamesInner";
import {
  GetAiGames200ResponseRecentGamesInnerFromJSON,
  GetAiGames200ResponseRecentGamesInnerFromJSONTyped,
  GetAiGames200ResponseRecentGamesInnerToJSON,
  GetAiGames200ResponseRecentGamesInnerToJSONTyped,
} from "./GetAiGames200ResponseRecentGamesInner";
import type { GetAiGames200ResponseTotal } from "./GetAiGames200ResponseTotal";
import {
  GetAiGames200ResponseTotalFromJSON,
  GetAiGames200ResponseTotalFromJSONTyped,
  GetAiGames200ResponseTotalToJSON,
  GetAiGames200ResponseTotalToJSONTyped,
} from "./GetAiGames200ResponseTotal";

/**
 *
 * @export
 * @interface GetAiGames200Response
 */
export interface GetAiGames200Response {
  /**
   *
   * @type {GetAiGames200ResponseTotal}
   * @memberof GetAiGames200Response
   */
  total: GetAiGames200ResponseTotal;
  /**
   *
   * @type {GetAiGames200ResponseByDifficulty}
   * @memberof GetAiGames200Response
   */
  byDifficulty: GetAiGames200ResponseByDifficulty;
  /**
   *
   * @type {Array<GetAiGames200ResponseRecentGamesInner>}
   * @memberof GetAiGames200Response
   */
  recentGames: Array<GetAiGames200ResponseRecentGamesInner>;
}

/**
 * Check if a given object implements the GetAiGames200Response interface.
 */
export function instanceOfGetAiGames200Response(
  value: object,
): value is GetAiGames200Response {
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("byDifficulty" in value) || value["byDifficulty"] === undefined)
    return false;
  if (!("recentGames" in value) || value["recentGames"] === undefined)
    return false;
  return true;
}

export function GetAiGames200ResponseFromJSON(
  json: any,
): GetAiGames200Response {
  return GetAiGames200ResponseFromJSONTyped(json, false);
}

export function GetAiGames200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAiGames200Response {
  if (json == null) {
    return json;
  }
  return {
    total: GetAiGames200ResponseTotalFromJSON(json["total"]),
    byDifficulty: GetAiGames200ResponseByDifficultyFromJSON(
      json["byDifficulty"],
    ),
    recentGames: (json["recentGames"] as Array<any>).map(
      GetAiGames200ResponseRecentGamesInnerFromJSON,
    ),
  };
}

export function GetAiGames200ResponseToJSON(json: any): GetAiGames200Response {
  return GetAiGames200ResponseToJSONTyped(json, false);
}

export function GetAiGames200ResponseToJSONTyped(
  value?: GetAiGames200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    total: GetAiGames200ResponseTotalToJSON(value["total"]),
    byDifficulty: GetAiGames200ResponseByDifficultyToJSON(
      value["byDifficulty"],
    ),
    recentGames: (value["recentGames"] as Array<any>).map(
      GetAiGames200ResponseRecentGamesInnerToJSON,
    ),
  };
}
