/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetAiGames200ResponseInner
 */
export interface GetAiGames200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseInner
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseInner
   */
  difficulty: GetAiGames200ResponseInnerDifficultyEnum;
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseInner
   */
  result: GetAiGames200ResponseInnerResultEnum;
  /**
   *
   * @type {Date}
   * @memberof GetAiGames200ResponseInner
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof GetAiGames200ResponseInner
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const GetAiGames200ResponseInnerDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type GetAiGames200ResponseInnerDifficultyEnum =
  (typeof GetAiGames200ResponseInnerDifficultyEnum)[keyof typeof GetAiGames200ResponseInnerDifficultyEnum];

/**
 * @export
 */
export const GetAiGames200ResponseInnerResultEnum = {
  Win: "win",
  Lose: "lose",
} as const;
export type GetAiGames200ResponseInnerResultEnum =
  (typeof GetAiGames200ResponseInnerResultEnum)[keyof typeof GetAiGames200ResponseInnerResultEnum];

/**
 * Check if a given object implements the GetAiGames200ResponseInner interface.
 */
export function instanceOfGetAiGames200ResponseInner(
  value: object,
): value is GetAiGames200ResponseInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function GetAiGames200ResponseInnerFromJSON(
  json: any,
): GetAiGames200ResponseInner {
  return GetAiGames200ResponseInnerFromJSONTyped(json, false);
}

export function GetAiGames200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAiGames200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    difficulty: json["difficulty"],
    result: json["result"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function GetAiGames200ResponseInnerToJSON(
  json: any,
): GetAiGames200ResponseInner {
  return GetAiGames200ResponseInnerToJSONTyped(json, false);
}

export function GetAiGames200ResponseInnerToJSONTyped(
  value?: GetAiGames200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    difficulty: value["difficulty"],
    result: value["result"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
