/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GetAiGames200ResponseTotal } from "./GetAiGames200ResponseTotal";
import {
  GetAiGames200ResponseTotalFromJSON,
  GetAiGames200ResponseTotalFromJSONTyped,
  GetAiGames200ResponseTotalToJSON,
  GetAiGames200ResponseTotalToJSONTyped,
} from "./GetAiGames200ResponseTotal";

/**
 *
 * @export
 * @interface GetAiGames200ResponseByDifficulty
 */
export interface GetAiGames200ResponseByDifficulty {
  /**
   *
   * @type {GetAiGames200ResponseTotal}
   * @memberof GetAiGames200ResponseByDifficulty
   */
  easy: GetAiGames200ResponseTotal;
  /**
   *
   * @type {GetAiGames200ResponseTotal}
   * @memberof GetAiGames200ResponseByDifficulty
   */
  medium: GetAiGames200ResponseTotal;
  /**
   *
   * @type {GetAiGames200ResponseTotal}
   * @memberof GetAiGames200ResponseByDifficulty
   */
  hard: GetAiGames200ResponseTotal;
}

/**
 * Check if a given object implements the GetAiGames200ResponseByDifficulty interface.
 */
export function instanceOfGetAiGames200ResponseByDifficulty(
  value: object,
): value is GetAiGames200ResponseByDifficulty {
  if (!("easy" in value) || value["easy"] === undefined) return false;
  if (!("medium" in value) || value["medium"] === undefined) return false;
  if (!("hard" in value) || value["hard"] === undefined) return false;
  return true;
}

export function GetAiGames200ResponseByDifficultyFromJSON(
  json: any,
): GetAiGames200ResponseByDifficulty {
  return GetAiGames200ResponseByDifficultyFromJSONTyped(json, false);
}

export function GetAiGames200ResponseByDifficultyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAiGames200ResponseByDifficulty {
  if (json == null) {
    return json;
  }
  return {
    easy: GetAiGames200ResponseTotalFromJSON(json["easy"]),
    medium: GetAiGames200ResponseTotalFromJSON(json["medium"]),
    hard: GetAiGames200ResponseTotalFromJSON(json["hard"]),
  };
}

export function GetAiGames200ResponseByDifficultyToJSON(
  json: any,
): GetAiGames200ResponseByDifficulty {
  return GetAiGames200ResponseByDifficultyToJSONTyped(json, false);
}

export function GetAiGames200ResponseByDifficultyToJSONTyped(
  value?: GetAiGames200ResponseByDifficulty | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    easy: GetAiGames200ResponseTotalToJSON(value["easy"]),
    medium: GetAiGames200ResponseTotalToJSON(value["medium"]),
    hard: GetAiGames200ResponseTotalToJSON(value["hard"]),
  };
}
