/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetAiGame200Response
 */
export interface GetAiGame200Response {
  /**
   *
   * @type {string}
   * @memberof GetAiGame200Response
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetAiGame200Response
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof GetAiGame200Response
   */
  difficulty: GetAiGame200ResponseDifficultyEnum;
  /**
   *
   * @type {string}
   * @memberof GetAiGame200Response
   */
  result: GetAiGame200ResponseResultEnum | null;
  /**
   *
   * @type {Date}
   * @memberof GetAiGame200Response
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof GetAiGame200Response
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const GetAiGame200ResponseDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type GetAiGame200ResponseDifficultyEnum =
  (typeof GetAiGame200ResponseDifficultyEnum)[keyof typeof GetAiGame200ResponseDifficultyEnum];

/**
 * @export
 */
export const GetAiGame200ResponseResultEnum = {
  Win: "win",
  Lose: "lose",
  Cancelled: "cancelled",
} as const;
export type GetAiGame200ResponseResultEnum =
  (typeof GetAiGame200ResponseResultEnum)[keyof typeof GetAiGame200ResponseResultEnum];

/**
 * Check if a given object implements the GetAiGame200Response interface.
 */
export function instanceOfGetAiGame200Response(
  value: object,
): value is GetAiGame200Response {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function GetAiGame200ResponseFromJSON(json: any): GetAiGame200Response {
  return GetAiGame200ResponseFromJSONTyped(json, false);
}

export function GetAiGame200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAiGame200Response {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    difficulty: json["difficulty"],
    result: json["result"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function GetAiGame200ResponseToJSON(json: any): GetAiGame200Response {
  return GetAiGame200ResponseToJSONTyped(json, false);
}

export function GetAiGame200ResponseToJSONTyped(
  value?: GetAiGame200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    difficulty: value["difficulty"],
    result: value["result"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
