/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetAiGames200ResponseTotal
 */
export interface GetAiGames200ResponseTotal {
  /**
   *
   * @type {number}
   * @memberof GetAiGames200ResponseTotal
   */
  wins: number;
  /**
   *
   * @type {number}
   * @memberof GetAiGames200ResponseTotal
   */
  losses: number;
}

/**
 * Check if a given object implements the GetAiGames200ResponseTotal interface.
 */
export function instanceOfGetAiGames200ResponseTotal(
  value: object,
): value is GetAiGames200ResponseTotal {
  if (!("wins" in value) || value["wins"] === undefined) return false;
  if (!("losses" in value) || value["losses"] === undefined) return false;
  return true;
}

export function GetAiGames200ResponseTotalFromJSON(
  json: any,
): GetAiGames200ResponseTotal {
  return GetAiGames200ResponseTotalFromJSONTyped(json, false);
}

export function GetAiGames200ResponseTotalFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAiGames200ResponseTotal {
  if (json == null) {
    return json;
  }
  return {
    wins: json["wins"],
    losses: json["losses"],
  };
}

export function GetAiGames200ResponseTotalToJSON(
  json: any,
): GetAiGames200ResponseTotal {
  return GetAiGames200ResponseTotalToJSONTyped(json, false);
}

export function GetAiGames200ResponseTotalToJSONTyped(
  value?: GetAiGames200ResponseTotal | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    wins: value["wins"],
    losses: value["losses"],
  };
}
