/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetAiGames200ResponseRecentGamesInner
 */
export interface GetAiGames200ResponseRecentGamesInner {
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseRecentGamesInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseRecentGamesInner
   */
  difficulty: GetAiGames200ResponseRecentGamesInnerDifficultyEnum;
  /**
   *
   * @type {string}
   * @memberof GetAiGames200ResponseRecentGamesInner
   */
  result: GetAiGames200ResponseRecentGamesInnerResultEnum;
  /**
   *
   * @type {Date}
   * @memberof GetAiGames200ResponseRecentGamesInner
   */
  createdAt: Date;
}

/**
 * @export
 */
export const GetAiGames200ResponseRecentGamesInnerDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type GetAiGames200ResponseRecentGamesInnerDifficultyEnum =
  (typeof GetAiGames200ResponseRecentGamesInnerDifficultyEnum)[keyof typeof GetAiGames200ResponseRecentGamesInnerDifficultyEnum];

/**
 * @export
 */
export const GetAiGames200ResponseRecentGamesInnerResultEnum = {
  Win: "win",
  Lose: "lose",
} as const;
export type GetAiGames200ResponseRecentGamesInnerResultEnum =
  (typeof GetAiGames200ResponseRecentGamesInnerResultEnum)[keyof typeof GetAiGames200ResponseRecentGamesInnerResultEnum];

/**
 * Check if a given object implements the GetAiGames200ResponseRecentGamesInner interface.
 */
export function instanceOfGetAiGames200ResponseRecentGamesInner(
  value: object,
): value is GetAiGames200ResponseRecentGamesInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function GetAiGames200ResponseRecentGamesInnerFromJSON(
  json: any,
): GetAiGames200ResponseRecentGamesInner {
  return GetAiGames200ResponseRecentGamesInnerFromJSONTyped(json, false);
}

export function GetAiGames200ResponseRecentGamesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAiGames200ResponseRecentGamesInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    difficulty: json["difficulty"],
    result: json["result"],
    createdAt: new Date(json["createdAt"]),
  };
}

export function GetAiGames200ResponseRecentGamesInnerToJSON(
  json: any,
): GetAiGames200ResponseRecentGamesInner {
  return GetAiGames200ResponseRecentGamesInnerToJSONTyped(json, false);
}

export function GetAiGames200ResponseRecentGamesInnerToJSONTyped(
  value?: GetAiGames200ResponseRecentGamesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    difficulty: value["difficulty"],
    result: value["result"],
    createdAt: value["createdAt"].toISOString(),
  };
}
