/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetCurrentUserResponse
 */
export interface GetCurrentUserResponse {
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  country?: string;
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  aiEasyWins: number;
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  aiEasyLosses: number;
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  aiMediumWins: number;
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  aiMediumLosses: number;
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  aiHardWins: number;
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  aiHardLosses: number;
  /**
   *
   * @type {Date}
   * @memberof GetCurrentUserResponse
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof GetCurrentUserResponse
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the GetCurrentUserResponse interface.
 */
export function instanceOfGetCurrentUserResponse(
  value: object,
): value is GetCurrentUserResponse {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  if (!("aiEasyWins" in value) || value["aiEasyWins"] === undefined)
    return false;
  if (!("aiEasyLosses" in value) || value["aiEasyLosses"] === undefined)
    return false;
  if (!("aiMediumWins" in value) || value["aiMediumWins"] === undefined)
    return false;
  if (!("aiMediumLosses" in value) || value["aiMediumLosses"] === undefined)
    return false;
  if (!("aiHardWins" in value) || value["aiHardWins"] === undefined)
    return false;
  if (!("aiHardLosses" in value) || value["aiHardLosses"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function GetCurrentUserResponseFromJSON(
  json: any,
): GetCurrentUserResponse {
  return GetCurrentUserResponseFromJSONTyped(json, false);
}

export function GetCurrentUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCurrentUserResponse {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"],
    displayName: json["displayName"],
    country: json["country"] == null ? undefined : json["country"],
    aiEasyWins: json["aiEasyWins"],
    aiEasyLosses: json["aiEasyLosses"],
    aiMediumWins: json["aiMediumWins"],
    aiMediumLosses: json["aiMediumLosses"],
    aiHardWins: json["aiHardWins"],
    aiHardLosses: json["aiHardLosses"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function GetCurrentUserResponseToJSON(
  json: any,
): GetCurrentUserResponse {
  return GetCurrentUserResponseToJSONTyped(json, false);
}

export function GetCurrentUserResponseToJSONTyped(
  value?: GetCurrentUserResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    displayName: value["displayName"],
    country: value["country"],
    aiEasyWins: value["aiEasyWins"],
    aiEasyLosses: value["aiEasyLosses"],
    aiMediumWins: value["aiMediumWins"],
    aiMediumLosses: value["aiMediumLosses"],
    aiHardWins: value["aiHardWins"],
    aiHardLosses: value["aiHardLosses"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
