/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetUser401Response
 */
export interface GetUser401Response {
  /**
   *
   * @type {string}
   * @memberof GetUser401Response
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof GetUser401Response
   */
  message: string;
}

/**
 * Check if a given object implements the GetUser401Response interface.
 */
export function instanceOfGetUser401Response(
  value: object,
): value is GetUser401Response {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function GetUser401ResponseFromJSON(json: any): GetUser401Response {
  return GetUser401ResponseFromJSONTyped(json, false);
}

export function GetUser401ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUser401Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    message: json["message"],
  };
}

export function GetUser401ResponseToJSON(json: any): GetUser401Response {
  return GetUser401ResponseToJSONTyped(json, false);
}

export function GetUser401ResponseToJSONTyped(
  value?: GetUser401Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    message: value["message"],
  };
}
