/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetUserResponse
 */
export interface GetUserResponse {
  /**
   *
   * @type {string}
   * @memberof GetUserResponse
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof GetUserResponse
   */
  displayName: string;
  /**
   *
   * @type {Date}
   * @memberof GetUserResponse
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof GetUserResponse
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the GetUserResponse interface.
 */
export function instanceOfGetUserResponse(
  value: object,
): value is GetUserResponse {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function GetUserResponseFromJSON(json: any): GetUserResponse {
  return GetUserResponseFromJSONTyped(json, false);
}

export function GetUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserResponse {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"],
    displayName: json["displayName"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function GetUserResponseToJSON(json: any): GetUserResponse {
  return GetUserResponseToJSONTyped(json, false);
}

export function GetUserResponseToJSONTyped(
  value?: GetUserResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    displayName: value["displayName"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
