/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RealtimeAiGame
 */
export interface RealtimeAiGame {
  /**
   *
   * @type {string}
   * @memberof RealtimeAiGame
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof RealtimeAiGame
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof RealtimeAiGame
   */
  difficulty: RealtimeAiGameDifficultyEnum;
  /**
   *
   * @type {number}
   * @memberof RealtimeAiGame
   */
  turn: RealtimeAiGameTurnEnum;
  /**
   *
   * @type {string}
   * @memberof RealtimeAiGame
   */
  country: string;
  /**
   *
   * @type {Array<string>}
   * @memberof RealtimeAiGame
   */
  borders: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof RealtimeAiGame
   */
  usedCountries: Array<string>;
  /**
   *
   * @type {Array<object>}
   * @memberof RealtimeAiGame
   */
  moves: Array<object>;
  /**
   *
   * @type {Date}
   * @memberof RealtimeAiGame
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof RealtimeAiGame
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const RealtimeAiGameDifficultyEnum = {
  Easy: "easy",
  Medium: "medium",
  Hard: "hard",
} as const;
export type RealtimeAiGameDifficultyEnum =
  (typeof RealtimeAiGameDifficultyEnum)[keyof typeof RealtimeAiGameDifficultyEnum];

/**
 * @export
 */
export const RealtimeAiGameTurnEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
export type RealtimeAiGameTurnEnum =
  (typeof RealtimeAiGameTurnEnum)[keyof typeof RealtimeAiGameTurnEnum];

/**
 * Check if a given object implements the RealtimeAiGame interface.
 */
export function instanceOfRealtimeAiGame(
  value: object,
): value is RealtimeAiGame {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("difficulty" in value) || value["difficulty"] === undefined)
    return false;
  if (!("turn" in value) || value["turn"] === undefined) return false;
  if (!("country" in value) || value["country"] === undefined) return false;
  if (!("borders" in value) || value["borders"] === undefined) return false;
  if (!("usedCountries" in value) || value["usedCountries"] === undefined)
    return false;
  if (!("moves" in value) || value["moves"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function RealtimeAiGameFromJSON(json: any): RealtimeAiGame {
  return RealtimeAiGameFromJSONTyped(json, false);
}

export function RealtimeAiGameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RealtimeAiGame {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    difficulty: json["difficulty"],
    turn: json["turn"],
    country: json["country"],
    borders: json["borders"],
    usedCountries: json["usedCountries"],
    moves: json["moves"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function RealtimeAiGameToJSON(json: any): RealtimeAiGame {
  return RealtimeAiGameToJSONTyped(json, false);
}

export function RealtimeAiGameToJSONTyped(
  value?: RealtimeAiGame | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    difficulty: value["difficulty"],
    turn: value["turn"],
    country: value["country"],
    borders: value["borders"],
    usedCountries: value["usedCountries"],
    moves: value["moves"],
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
