/* tslint:disable */
/* eslint-disable */
/**
 * GeoChess Server API
 * API specification for the GeoChess server.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  country?: string;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(
  value: object,
): value is UpdateUserRequest {
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserRequest {
  if (json == null) {
    return json;
  }
  return {
    displayName: json["displayName"],
    country: json["country"] == null ? undefined : json["country"],
  };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(
  value?: UpdateUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    displayName: value["displayName"],
    country: value["country"],
  };
}
