/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AiGameMove": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiGameMoveDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiGameTimeout": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiGameTimeoutDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiMoveWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AiTimeoutWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CleanupAiGames": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CleanupFriendsGames": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FriendsStartWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FriendsTimeoutWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WithFriendsGameStart": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsGameStartDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsGameTimeout": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsGameTimeoutDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}

import "sst"
export {}