/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AiGameMoveDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiGameMoveQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiGameTimeoutDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AiGameTimeoutQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WithFriendsGameStartDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsGameStartQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsGameTimeoutDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsGameTimeoutQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}

import "sst"
export {}