# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class AiGameMoveDLQ:
        type: str
        url: str
    class AiGameMoveQueue:
        type: str
        url: str
    class AiGameTimeoutDLQ:
        type: str
        url: str
    class AiGameTimeoutQueue:
        type: str
        url: str
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str

