const countryNames = {
  ad: {
    de: "Andorra",
    en: "Andorra",
    es: "Andorra",
    fr: "Andorre",
    ja: "アンドラ",
    pt: "Andorra",
    zh: "安道尔",
  },
  ae: {
    de: "Vereinigte Arabische Emirate",
    en: "United Arab Emirates",
    es: "Emiratos Árabes Unidos",
    fr: "Émirats arabes unis",
    ja: "アラブ首長国連邦",
    pt: "Emirados Árabes Unidos",
    zh: "阿拉伯联合酋长国",
  },
  af: {
    de: "Afghanistan",
    en: "Afghanistan",
    es: "Afganistán",
    fr: "Afghanistan",
    ja: "アフガニスタン",
    pt: "Afeganistão",
    zh: "阿富汗",
  },
  ag: {
    de: "Antigua und Barbuda",
    en: "Antigua and Barbuda",
    es: "Antigua y Barbuda",
    fr: "Antigua-et-Barbuda",
    ja: "アンティグア・バーブーダ",
    pt: "Antígua e Barbuda",
    zh: "安提瓜和巴布达",
  },
  ai: {
    de: "Anguilla",
    en: "Anguilla",
    es: "Anguilla",
    fr: "Anguilla",
    ja: "アンギラ",
    pt: "Anguilla",
    zh: "安圭拉",
  },
  al: {
    de: "Albanien",
    en: "Albania",
    es: "Albania",
    fr: "Albanie",
    ja: "アルバニア",
    pt: "Albânia",
    zh: "阿尔巴尼亚",
  },
  am: {
    de: "Armenien",
    en: "Armenia",
    es: "Armenia",
    fr: "Arménie",
    ja: "アルメニア",
    pt: "Arménia",
    zh: "亚美尼亚",
  },
  ao: {
    de: "Angola",
    en: "Angola",
    es: "Angola",
    fr: "Angola",
    ja: "アンゴラ",
    pt: "Angola",
    zh: "安哥拉",
  },
  aq: {
    de: "Antarktis",
    en: "Antarctica",
    es: "Antártida",
    fr: "Antarctique",
    ja: "南極",
    pt: "Antártida",
    zh: "南极洲",
  },
  ar: {
    de: "Argentinien",
    en: "Argentina",
    es: "Argentina",
    fr: "Argentine",
    ja: "アルゼンチン",
    pt: "Argentina",
    zh: "阿根廷",
  },
  as: {
    de: "Amerikanisch-Samoa",
    en: "American Samoa",
    es: "Samoa Americana",
    fr: "Samoa américaines",
    ja: "アメリカ領サモア",
    pt: "Samoa Americana",
    zh: "美属萨摩亚",
  },
  at: {
    de: "Österreich",
    en: "Austria",
    es: "Austria",
    fr: "Autriche",
    ja: "オーストリア",
    pt: "Áustria",
    zh: "奥地利",
  },
  au: {
    de: "Australien",
    en: "Australia",
    es: "Australia",
    fr: "Australie",
    ja: "オーストラリア",
    pt: "Austrália",
    zh: "澳大利亚",
  },
  aw: {
    de: "Aruba",
    en: "Aruba",
    es: "Aruba",
    fr: "Aruba",
    ja: "アルバ",
    pt: "Aruba",
    zh: "阿鲁巴",
  },
  ax: {
    de: "Åland",
    en: "Åland Islands",
    es: "Alandia",
    fr: "Ahvenanmaa",
    ja: "オーランド諸島",
    pt: "Alândia",
    zh: "奥兰群岛",
  },
  az: {
    de: "Aserbaidschan",
    en: "Azerbaijan",
    es: "Azerbaiyán",
    fr: "Azerbaïdjan",
    ja: "アゼルバイジャン",
    pt: "Azerbeijão",
    zh: "阿塞拜疆",
  },
  ba: {
    de: "Bosnien und Herzegowina",
    en: "Bosnia and Herzegovina",
    es: "Bosnia y Herzegovina",
    fr: "Bosnie-Herzégovine",
    ja: "ボスニア・ヘルツェゴビナ",
    pt: "Bósnia e Herzegovina",
    zh: "波斯尼亚和黑塞哥维那",
  },
  bb: {
    de: "Barbados",
    en: "Barbados",
    es: "Barbados",
    fr: "Barbade",
    ja: "バルバドス",
    pt: "Barbados",
    zh: "巴巴多斯",
  },
  bd: {
    de: "Bangladesch",
    en: "Bangladesh",
    es: "Bangladesh",
    fr: "Bangladesh",
    ja: "バングラデシュ",
    pt: "Bangladesh",
    zh: "孟加拉国",
  },
  be: {
    de: "Belgien",
    en: "Belgium",
    es: "Bélgica",
    fr: "Belgique",
    ja: "ベルギー",
    pt: "Bélgica",
    zh: "比利时",
  },
  bf: {
    de: "Burkina Faso",
    en: "Burkina Faso",
    es: "Burkina Faso",
    fr: "Burkina Faso",
    ja: "ブルキナファソ",
    pt: "Burkina Faso",
    zh: "布基纳法索",
  },
  bg: {
    de: "Bulgarien",
    en: "Bulgaria",
    es: "Bulgaria",
    fr: "Bulgarie",
    ja: "ブルガリア",
    pt: "Bulgária",
    zh: "保加利亚",
  },
  bh: {
    de: "Bahrain",
    en: "Bahrain",
    es: "Bahrein",
    fr: "Bahreïn",
    ja: "バーレーン",
    pt: "Bahrein",
    zh: "巴林",
  },
  bi: {
    de: "Burundi",
    en: "Burundi",
    es: "Burundi",
    fr: "Burundi",
    ja: "ブルンジ",
    pt: "Burundi",
    zh: "布隆迪",
  },
  bj: {
    de: "Benin",
    en: "Benin",
    es: "Benín",
    fr: "Bénin",
    ja: "ベナン",
    pt: "Benin",
    zh: "贝宁",
  },
  bl: {
    de: "Saint-Barthélemy",
    en: "Saint Barthélemy",
    es: "San Bartolomé",
    fr: "Saint-Barthélemy",
    ja: "サン・バルテルミー",
    pt: "São Bartolomeu",
    zh: "圣巴泰勒米",
  },
  bm: {
    de: "Bermuda",
    en: "Bermuda",
    es: "Bermudas",
    fr: "Bermudes",
    ja: "バミューダ",
    pt: "Bermudas",
    zh: "百慕大",
  },
  bn: {
    de: "Brunei",
    en: "Brunei",
    es: "Brunei",
    fr: "Brunei",
    ja: "ブルネイ・ダルサラーム",
    pt: "Brunei",
    zh: "文莱",
  },
  bo: {
    de: "Bolivien",
    en: "Bolivia",
    es: "Bolivia",
    fr: "Bolivie",
    ja: "ボリビア多民族国",
    pt: "Bolívia",
    zh: "玻利维亚",
  },
  bq: {
    de: "Karibische Niederlande",
    en: "Caribbean Netherlands",
    es: "Caribe Neerlandés",
    fr: "Pays-Bas caribéens",
    ja: "ボネール、シント・ユースタティウスおよびサバ",
    pt: "Países Baixos Caribenhos",
    zh: "荷蘭加勒比區",
  },
  br: {
    de: "Brasilien",
    en: "Brazil",
    es: "Brasil",
    fr: "Brésil",
    ja: "ブラジル",
    pt: "Brasil",
    zh: "巴西",
  },
  bs: {
    de: "Bahamas",
    en: "Bahamas",
    es: "Bahamas",
    fr: "Bahamas",
    ja: "バハマ",
    pt: "Bahamas",
    zh: "巴哈马",
  },
  bt: {
    de: "Bhutan",
    en: "Bhutan",
    es: "Bután",
    fr: "Bhoutan",
    ja: "ブータン",
    pt: "Butão",
    zh: "不丹",
  },
  bv: {
    de: "Bouvetinsel",
    en: "Bouvet Island",
    es: "Isla Bouvet",
    fr: "Île Bouvet",
    ja: "ブーベ島",
    pt: "Ilha Bouvet",
    zh: "布维岛",
  },
  bw: {
    de: "Botswana",
    en: "Botswana",
    es: "Botswana",
    fr: "Botswana",
    ja: "ボツワナ",
    pt: "Botswana",
    zh: "博茨瓦纳",
  },
  by: {
    de: "Weißrussland",
    en: "Belarus",
    es: "Bielorrusia",
    fr: "Biélorussie",
    ja: "ベラルーシ",
    pt: "Bielorússia",
    zh: "白俄罗斯",
  },
  bz: {
    de: "Belize",
    en: "Belize",
    es: "Belice",
    fr: "Belize",
    ja: "ベリーズ",
    pt: "Belize",
    zh: "伯利兹",
  },
  ca: {
    de: "Kanada",
    en: "Canada",
    es: "Canadá",
    fr: "Canada",
    ja: "カナダ",
    pt: "Canadá",
    zh: "加拿大",
  },
  cc: {
    de: "Kokosinseln",
    en: "Cocos (Keeling) Islands",
    es: "Islas Cocos o Islas Keeling",
    fr: "Îles Cocos",
    ja: "ココス（キーリング）諸島",
    pt: "Ilhas Cocos (Keeling)",
    zh: "科科斯",
  },
  cd: {
    de: "Kongo (Dem. Rep.)",
    en: "DRC",
    es: "Congo (Rep. Dem.)",
    fr: "Congo (Rép. dém.)",
    ja: "コンゴ民主共和国",
    pt: "República Democrática do Congo",
    zh: "民主刚果",
  },
  cf: {
    de: "Zentralafrikanische Republik",
    en: "Central African Republic",
    es: "República Centroafricana",
    fr: "République centrafricaine",
    ja: "中央アフリカ共和国",
    pt: "República Centro-Africana",
    zh: "中非共和国",
  },
  cg: {
    de: "Kongo",
    en: "Congo",
    es: "Congo",
    fr: "Congo",
    ja: "コンゴ共和国",
    pt: "Congo",
    zh: "刚果",
  },
  ch: {
    de: "Schweiz",
    en: "Switzerland",
    es: "Suiza",
    fr: "Suisse",
    ja: "スイス",
    pt: "Suíça",
    zh: "瑞士",
  },
  ci: {
    de: "Elfenbeinküste",
    en: "Ivory Coast",
    es: "Costa de Marfil",
    fr: "Côte d'Ivoire",
    ja: "コートジボワール",
    pt: "Costa do Marfim",
    zh: "科特迪瓦",
  },
  ck: {
    de: "Cookinseln",
    en: "Cook Islands",
    es: "Islas Cook",
    fr: "Îles Cook",
    ja: "クック諸島",
    pt: "Ilhas Cook",
    zh: "库克群岛",
  },
  cl: {
    de: "Chile",
    en: "Chile",
    es: "Chile",
    fr: "Chili",
    ja: "チリ",
    pt: "Chile",
    zh: "智利",
  },
  cm: {
    de: "Kamerun",
    en: "Cameroon",
    es: "Camerún",
    fr: "Cameroun",
    ja: "カメルーン",
    pt: "Camarões",
    zh: "喀麦隆",
  },
  cn: {
    de: "China",
    en: "China",
    es: "China",
    fr: "Chine",
    ja: "中国",
    pt: "China",
    zh: "China",
  },
  co: {
    de: "Kolumbien",
    en: "Colombia",
    es: "Colombia",
    fr: "Colombie",
    ja: "コロンビア",
    pt: "Colômbia",
    zh: "哥伦比亚",
  },
  cr: {
    de: "Costa Rica",
    en: "Costa Rica",
    es: "Costa Rica",
    fr: "Costa Rica",
    ja: "コスタリカ",
    pt: "Costa Rica",
    zh: "哥斯达黎加",
  },
  cu: {
    de: "Kuba",
    en: "Cuba",
    es: "Cuba",
    fr: "Cuba",
    ja: "キューバ",
    pt: "Cuba",
    zh: "古巴",
  },
  cv: {
    de: "Kap Verde",
    en: "Cabo Verde",
    es: "Cabo Verde",
    fr: "Îles du Cap-Vert",
    ja: "カーボベルデ",
    pt: "Cabo Verde",
    zh: "佛得角",
  },
  cw: {
    de: "Curaçao",
    en: "Curaçao",
    es: "Curazao",
    fr: "Curaçao",
    ja: "Curaçao",
    pt: "ilha da Curação",
    zh: "库拉索",
  },
  cx: {
    de: "Weihnachtsinsel",
    en: "Christmas Island",
    es: "Isla de Navidad",
    fr: "Île Christmas",
    ja: "クリスマス島",
    pt: "Ilha do Natal",
    zh: "圣诞岛",
  },
  cy: {
    de: "Zypern",
    en: "Cyprus",
    es: "Chipre",
    fr: "Chypre",
    ja: "キプロス",
    pt: "Chipre",
    zh: "塞浦路斯",
  },
  cz: {
    de: "Tschechien",
    en: "Czechia",
    es: "Chequia",
    fr: "Tchéquie",
    ja: "チェコ",
    pt: "Chéquia",
    zh: "捷克",
  },
  de: {
    de: "Deutschland",
    en: "Germany",
    es: "Alemania",
    fr: "Allemagne",
    ja: "ドイツ",
    pt: "Alemanha",
    zh: "德国",
  },
  dj: {
    de: "Dschibuti",
    en: "Djibouti",
    es: "Djibouti",
    fr: "Djibouti",
    ja: "ジブチ",
    pt: "Djibouti",
    zh: "吉布提",
  },
  dk: {
    de: "Dänemark",
    en: "Denmark",
    es: "Dinamarca",
    fr: "Danemark",
    ja: "デンマーク",
    pt: "Dinamarca",
    zh: "丹麦",
  },
  dm: {
    de: "Dominica",
    en: "Dominica",
    es: "Dominica",
    fr: "Dominique",
    ja: "ドミニカ国",
    pt: "Dominica",
    zh: "多米尼加",
  },
  do: {
    de: "Dominikanische Republik",
    en: "Dominican Republic",
    es: "República Dominicana",
    fr: "République dominicaine",
    ja: "ドミニカ共和国",
    pt: "República Dominicana",
    zh: "多明尼加",
  },
  dz: {
    de: "Algerien",
    en: "Algeria",
    es: "Argelia",
    fr: "Algérie",
    ja: "アルジェリア",
    pt: "Argélia",
    zh: "阿尔及利亚",
  },
  ec: {
    de: "Ecuador",
    en: "Ecuador",
    es: "Ecuador",
    fr: "Équateur",
    ja: "エクアドル",
    pt: "Equador",
    zh: "厄瓜多尔",
  },
  ee: {
    de: "Estland",
    en: "Estonia",
    es: "Estonia",
    fr: "Estonie",
    ja: "エストニア",
    pt: "Estónia",
    zh: "爱沙尼亚",
  },
  eg: {
    de: "Ägypten",
    en: "Egypt",
    es: "Egipto",
    fr: "Égypte",
    ja: "エジプト",
    pt: "Egito",
    zh: "埃及",
  },
  eh: {
    de: "Westsahara",
    en: "Western Sahara",
    es: "Sahara Occidental",
    fr: "Sahara Occidental",
    ja: "西サハラ",
    pt: "Saara Ocidental",
    zh: "西撒哈拉",
  },
  er: {
    de: "Eritrea",
    en: "Eritrea",
    es: "Eritrea",
    fr: "Érythrée",
    ja: "エリトリア",
    pt: "Eritreia",
    zh: "厄立特里亚",
  },
  es: {
    de: "Spanien",
    en: "Spain",
    es: "España",
    fr: "Espagne",
    ja: "スペイン",
    pt: "Espanha",
    zh: "西班牙",
  },
  et: {
    de: "Äthiopien",
    en: "Ethiopia",
    es: "Etiopía",
    fr: "Éthiopie",
    ja: "エチオピア",
    pt: "Etiópia",
    zh: "埃塞俄比亚",
  },
  fi: {
    de: "Finnland",
    en: "Finland",
    es: "Finlandia",
    fr: "Finlande",
    ja: "フィンランド",
    pt: "Finlândia",
    zh: "芬兰",
  },
  fj: {
    de: "Fidschi",
    en: "Fiji",
    es: "Fiyi",
    fr: "Fidji",
    ja: "フィジー",
    pt: "Fiji",
    zh: "斐济",
  },
  fk: {
    de: "Falklandinseln",
    en: "Falkland Islands",
    es: "Islas Malvinas",
    fr: "Îles Malouines",
    ja: "フォークランド（マルビナス）諸島",
    pt: "Ilhas Malvinas",
    zh: "福克兰群岛",
  },
  fm: {
    de: "Mikronesien",
    en: "Micronesia",
    es: "Micronesia",
    fr: "Micronésie",
    ja: "ミクロネシア連邦",
    pt: "Micronésia",
    zh: "密克罗尼西亚",
  },
  fo: {
    de: "Färöer-Inseln",
    en: "Faroe Islands",
    es: "Islas Faroe",
    fr: "Îles Féroé",
    ja: "フェロー諸島",
    pt: "Ilhas Faroé",
    zh: "法罗群岛",
  },
  fr: {
    de: "Frankreich",
    en: "France",
    es: "Francia",
    fr: "France",
    ja: "フランス",
    pt: "França",
    zh: "法国",
  },
  ga: {
    de: "Gabun",
    en: "Gabon",
    es: "Gabón",
    fr: "Gabon",
    ja: "ガボン",
    pt: "Gabão",
    zh: "加蓬",
  },
  gb: {
    de: "Vereinigtes Königreich",
    en: "United Kingdom",
    es: "Reino Unido",
    fr: "Royaume-Uni",
    ja: "イギリス",
    pt: "Reino Unido",
    zh: "英国",
  },
  gd: {
    de: "Grenada",
    en: "Grenada",
    es: "Grenada",
    fr: "Grenade",
    ja: "グレナダ",
    pt: "Granada",
    zh: "格林纳达",
  },
  ge: {
    de: "Georgien",
    en: "Georgia",
    es: "Georgia",
    fr: "Géorgie",
    ja: "グルジア",
    pt: "Geórgia",
    zh: "格鲁吉亚",
  },
  gf: {
    de: "Französisch-Guayana",
    en: "French Guiana",
    es: "Guayana Francesa",
    fr: "Guyane",
    ja: "フランス領ギアナ",
    pt: "Guiana Francesa",
    zh: "法属圭亚那",
  },
  gg: {
    de: "Guernsey",
    en: "Guernsey",
    es: "Guernsey",
    fr: "Guernesey",
    ja: "ガーンジー",
    pt: "Guernsey",
    zh: "根西岛",
  },
  gh: {
    de: "Ghana",
    en: "Ghana",
    es: "Ghana",
    fr: "Ghana",
    ja: "ガーナ",
    pt: "Gana",
    zh: "加纳",
  },
  gi: {
    de: "Gibraltar",
    en: "Gibraltar",
    es: "Gibraltar",
    fr: "Gibraltar",
    ja: "ジブラルタル",
    pt: "Gibraltar",
    zh: "直布罗陀",
  },
  gl: {
    de: "Grönland",
    en: "Greenland",
    es: "Groenlandia",
    fr: "Groenland",
    ja: "グリーンランド",
    pt: "Gronelândia",
    zh: "格陵兰",
  },
  gm: {
    de: "Gambia",
    en: "Gambia",
    es: "Gambia",
    fr: "Gambie",
    ja: "ガンビア",
    pt: "Gâmbia",
    zh: "冈比亚",
  },
  gn: {
    de: "Guinea",
    en: "Guinea",
    es: "Guinea",
    fr: "Guinée",
    ja: "ギニア",
    pt: "Guiné",
    zh: "几内亚",
  },
  gp: {
    de: "Guadeloupe",
    en: "Guadeloupe",
    es: "Guadalupe",
    fr: "Guadeloupe",
    ja: "グアドループ",
    pt: "Guadalupe",
    zh: "瓜德罗普岛",
  },
  gq: {
    de: "Äquatorialguinea",
    en: "Equatorial Guinea",
    es: "Guinea Ecuatorial",
    fr: "Guinée équatoriale",
    ja: "赤道ギニア",
    pt: "Guiné Equatorial",
    zh: "赤道几内亚",
  },
  gr: {
    de: "Griechenland",
    en: "Greece",
    es: "Grecia",
    fr: "Grèce",
    ja: "ギリシャ",
    pt: "Grécia",
    zh: "希腊",
  },
  gs: {
    de: "Südgeorgien und die Südlichen Sandwichinseln",
    en: "South Georgia",
    es: "Islas Georgias del Sur y Sandwich del Sur",
    fr: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    ja: "サウスジョージア・サウスサンドウィッチ諸島",
    pt: "Ilhas Geórgia do Sul e Sandwich do Sul",
    zh: "南乔治亚",
  },
  gt: {
    de: "Guatemala",
    en: "Guatemala",
    es: "Guatemala",
    fr: "Guatemala",
    ja: "グアテマラ",
    pt: "Guatemala",
    zh: "危地马拉",
  },
  gu: {
    de: "Guam",
    en: "Guam",
    es: "Guam",
    fr: "Guam",
    ja: "グアム",
    pt: "Guam",
    zh: "关岛",
  },
  gw: {
    de: "Guinea-Bissau",
    en: "Guinea-Bissau",
    es: "Guinea-Bisáu",
    fr: "Guinée-Bissau",
    ja: "ギニアビサウ",
    pt: "Guiné-Bissau",
    zh: "几内亚比绍",
  },
  gy: {
    de: "Guyana",
    en: "Guyana",
    es: "Guyana",
    fr: "Guyana",
    ja: "ガイアナ",
    pt: "Guiana",
    zh: "圭亚那",
  },
  hk: {
    de: "Hongkong",
    en: "Hong Kong",
    es: "Hong Kong",
    fr: "Hong Kong",
    ja: "香港",
    pt: "Hong Kong",
    zh: "Hong Kong",
  },
  hm: {
    de: "Heard und die McDonaldinseln",
    en: "Heard Island and McDonald Islands",
    es: "Islas Heard y McDonald",
    fr: "Îles Heard-et-MacDonald",
    ja: "ハード島とマクドナルド諸島",
    pt: "Ilha Heard e Ilhas McDonald",
    zh: "赫德岛和麦当劳群岛",
  },
  hn: {
    de: "Honduras",
    en: "Honduras",
    es: "Honduras",
    fr: "Honduras",
    ja: "ホンジュラス",
    pt: "Honduras",
    zh: "洪都拉斯",
  },
  hr: {
    de: "Kroatien",
    en: "Croatia",
    es: "Croacia",
    fr: "Croatie",
    ja: "クロアチア",
    pt: "Croácia",
    zh: "克罗地亚",
  },
  ht: {
    de: "Haiti",
    en: "Haiti",
    es: "Haití",
    fr: "Haïti",
    ja: "ハイチ",
    pt: "Haiti",
    zh: "海地",
  },
  hu: {
    de: "Ungarn",
    en: "Hungary",
    es: "Hungría",
    fr: "Hongrie",
    ja: "ハンガリー",
    pt: "Hungria",
    zh: "匈牙利",
  },
  id: {
    de: "Indonesien",
    en: "Indonesia",
    es: "Indonesia",
    fr: "Indonésie",
    ja: "インドネシア",
    pt: "Indonésia",
    zh: "印度尼西亚",
  },
  ie: {
    de: "Irland",
    en: "Ireland",
    es: "Irlanda",
    fr: "Irlande",
    ja: "アイルランド",
    pt: "Irlanda",
    zh: "爱尔兰",
  },
  il: {
    de: "Israel",
    en: "Israel",
    es: "Israel",
    fr: "Israël",
    ja: "イスラエル",
    pt: "Israel",
    zh: "以色列",
  },
  im: {
    de: "Insel Man",
    en: "Isle of Man",
    es: "Isla de Man",
    fr: "Île de Man",
    ja: "マン島",
    pt: "Ilha de Man",
    zh: "马恩岛",
  },
  in: {
    de: "Indien",
    en: "India",
    es: "India",
    fr: "Inde",
    ja: "インド",
    pt: "Índia",
    zh: "印度",
  },
  io: {
    de: "Britisches Territorium im Indischen Ozean",
    en: "British Indian Ocean Territory",
    es: "Territorio Británico del Océano Índico",
    fr: "Territoire britannique de l'océan Indien",
    ja: "イギリス領インド洋地域",
    pt: "Território Britânico do Oceano Índico",
    zh: "英属印度洋领地",
  },
  iq: {
    de: "Irak",
    en: "Iraq",
    es: "Irak",
    fr: "Irak",
    ja: "イラク",
    pt: "Iraque",
    zh: "伊拉克",
  },
  ir: {
    de: "Iran",
    en: "Iran",
    es: "Iran",
    fr: "Iran",
    ja: "イラン・イスラム共和国",
    pt: "Irão",
    zh: "伊朗",
  },
  is: {
    de: "Island",
    en: "Iceland",
    es: "Islandia",
    fr: "Islande",
    ja: "アイスランド",
    pt: "Islândia",
    zh: "冰岛",
  },
  it: {
    de: "Italien",
    en: "Italy",
    es: "Italia",
    fr: "Italie",
    ja: "イタリア",
    pt: "Itália",
    zh: "意大利",
  },
  je: {
    de: "Jersey",
    en: "Jersey",
    es: "Jersey",
    fr: "Jersey",
    ja: "ジャージー",
    pt: "Jersey",
    zh: "泽西岛",
  },
  jm: {
    de: "Jamaika",
    en: "Jamaica",
    es: "Jamaica",
    fr: "Jamaïque",
    ja: "ジャマイカ",
    pt: "Jamaica",
    zh: "牙买加",
  },
  jo: {
    de: "Jordanien",
    en: "Jordan",
    es: "Jordania",
    fr: "Jordanie",
    ja: "ヨルダン",
    pt: "Jordânia",
    zh: "约旦",
  },
  jp: {
    de: "Japan",
    en: "Japan",
    es: "Japón",
    fr: "Japon",
    ja: "日本",
    pt: "Japão",
    zh: "日本",
  },
  ke: {
    de: "Kenia",
    en: "Kenya",
    es: "Kenia",
    fr: "Kenya",
    ja: "ケニア",
    pt: "Quénia",
    zh: "肯尼亚",
  },
  kg: {
    de: "Kirgisistan",
    en: "Kyrgyzstan",
    es: "Kirguizistán",
    fr: "Kirghizistan",
    ja: "キルギス",
    pt: "Quirguistão",
    zh: "吉尔吉斯斯坦",
  },
  kh: {
    de: "Kambodscha",
    en: "Cambodia",
    es: "Camboya",
    fr: "Cambodge",
    ja: "カンボジア",
    pt: "Camboja",
    zh: "柬埔寨",
  },
  ki: {
    de: "Kiribati",
    en: "Kiribati",
    es: "Kiribati",
    fr: "Kiribati",
    ja: "キリバス",
    pt: "Kiribati",
    zh: "基里巴斯",
  },
  km: {
    de: "Komoren",
    en: "Comoros",
    es: "Comoras",
    fr: "Comores",
    ja: "コモロ",
    pt: "Comores",
    zh: "科摩罗",
  },
  kn: {
    de: "St. Kitts und Nevis",
    en: "Saint Kitts and Nevis",
    es: "San Cristóbal y Nieves",
    fr: "Saint-Christophe-et-Niévès",
    ja: "セントクリストファー・ネイビス",
    pt: "São Cristóvão e Nevis",
    zh: "圣基茨和尼维斯",
  },
  kp: {
    de: "Nordkorea",
    en: "North Korea",
    es: "Corea del Norte",
    fr: "Corée du Nord",
    ja: "朝鮮民主主義人民共和国",
    pt: "Coreia do Norte",
    zh: "朝鲜",
  },
  kr: {
    de: "Südkorea",
    en: "South Korea",
    es: "Corea del Sur",
    fr: "Corée du Sud",
    ja: "韓国",
    pt: "Coreia do Sul",
    zh: "韩国",
  },
  kw: {
    de: "Kuwait",
    en: "Kuwait",
    es: "Kuwait",
    fr: "Koweït",
    ja: "クウェート",
    pt: "Kuwait",
    zh: "科威特",
  },
  ky: {
    de: "Kaimaninseln",
    en: "Cayman Islands",
    es: "Islas Caimán",
    fr: "Îles Caïmans",
    ja: "ケイマン諸島",
    pt: "Ilhas Caimão",
    zh: "开曼群岛",
  },
  kz: {
    de: "Kasachstan",
    en: "Kazakhstan",
    es: "Kazajistán",
    fr: "Kazakhstan",
    ja: "カザフスタン",
    pt: "Cazaquistão",
    zh: "哈萨克斯坦",
  },
  la: {
    de: "Laos",
    en: "Laos",
    es: "Laos",
    fr: "Laos",
    ja: "ラオス人民民主共和国",
    pt: "Laos",
    zh: "老挝",
  },
  lb: {
    de: "Libanon",
    en: "Lebanon",
    es: "Líbano",
    fr: "Liban",
    ja: "レバノン",
    pt: "Líbano",
    zh: "黎巴嫩",
  },
  lc: {
    de: "St. Lucia",
    en: "Saint Lucia",
    es: "Santa Lucía",
    fr: "Sainte-Lucie",
    ja: "セントルシア",
    pt: "Santa Lúcia",
    zh: "圣卢西亚",
  },
  li: {
    de: "Liechtenstein",
    en: "Liechtenstein",
    es: "Liechtenstein",
    fr: "Liechtenstein",
    ja: "リヒテンシュタイン",
    pt: "Liechtenstein",
    zh: "列支敦士登",
  },
  lk: {
    de: "Sri Lanka",
    en: "Sri Lanka",
    es: "Sri Lanka",
    fr: "Sri Lanka",
    ja: "スリランカ",
    pt: "Sri Lanka",
    zh: "斯里兰卡",
  },
  lr: {
    de: "Liberia",
    en: "Liberia",
    es: "Liberia",
    fr: "Liberia",
    ja: "リベリア",
    pt: "Libéria",
    zh: "利比里亚",
  },
  ls: {
    de: "Lesotho",
    en: "Lesotho",
    es: "Lesotho",
    fr: "Lesotho",
    ja: "レソト",
    pt: "Lesoto",
    zh: "莱索托",
  },
  lt: {
    de: "Litauen",
    en: "Lithuania",
    es: "Lituania",
    fr: "Lituanie",
    ja: "リトアニア",
    pt: "Lituânia",
    zh: "立陶宛",
  },
  lu: {
    de: "Luxemburg",
    en: "Luxembourg",
    es: "Luxemburgo",
    fr: "Luxembourg",
    ja: "ルクセンブルク",
    pt: "Luxemburgo",
    zh: "卢森堡",
  },
  lv: {
    de: "Lettland",
    en: "Latvia",
    es: "Letonia",
    fr: "Lettonie",
    ja: "ラトビア",
    pt: "Letónia",
    zh: "拉脱维亚",
  },
  ly: {
    de: "Libyen",
    en: "Libya",
    es: "Libia",
    fr: "Libye",
    ja: "リビア",
    pt: "Líbia",
    zh: "利比亚",
  },
  ma: {
    de: "Marokko",
    en: "Morocco",
    es: "Marruecos",
    fr: "Maroc",
    ja: "モロッコ",
    pt: "Marrocos",
    zh: "摩洛哥",
  },
  mc: {
    de: "Monaco",
    en: "Monaco",
    es: "Mónaco",
    fr: "Monaco",
    ja: "モナコ",
    pt: "Mónaco",
    zh: "摩纳哥",
  },
  md: {
    de: "Moldawien",
    en: "Moldova",
    es: "Moldavia",
    fr: "Moldavie",
    ja: "モルドバ共和国",
    pt: "Moldávia",
    zh: "摩尔多瓦",
  },
  me: {
    de: "Montenegro",
    en: "Montenegro",
    es: "Montenegro",
    fr: "Monténégro",
    ja: "モンテネグロ",
    pt: "Montenegro",
    zh: "黑山",
  },
  mf: {
    de: "Saint-Martin",
    en: "Saint Martin",
    es: "Saint Martin",
    fr: "Saint-Martin",
    ja: "サン・マルタン（フランス領）",
    pt: "São Martinho",
    zh: "圣马丁",
  },
  mg: {
    de: "Madagaskar",
    en: "Madagascar",
    es: "Madagascar",
    fr: "Madagascar",
    ja: "マダガスカル",
    pt: "Madagáscar",
    zh: "马达加斯加",
  },
  mh: {
    de: "Marshallinseln",
    en: "Marshall Islands",
    es: "Islas Marshall",
    fr: "Îles Marshall",
    ja: "マーシャル諸島",
    pt: "Ilhas Marshall",
    zh: "马绍尔群岛",
  },
  mk: {
    de: "Nordmazedonien",
    en: "North Macedonia",
    es: "Macedonia del Norte",
    fr: "Macédoine du Nord",
    ja: "北マケドニア ",
    pt: "Macedónia do Norte",
    zh: "北馬其頓",
  },
  ml: {
    de: "Mali",
    en: "Mali",
    es: "Mali",
    fr: "Mali",
    ja: "マリ",
    pt: "Mali",
    zh: "马里",
  },
  mm: {
    de: "Myanmar",
    en: "Myanmar",
    es: "Myanmar",
    fr: "Birmanie",
    ja: "ミャンマー",
    pt: "Myanmar",
    zh: "缅甸",
  },
  mn: {
    de: "Mongolei",
    en: "Mongolia",
    es: "Mongolia",
    fr: "Mongolie",
    ja: "モンゴル",
    pt: "Mongólia",
    zh: "蒙古",
  },
  mo: {
    de: "Macao",
    en: "Macau",
    es: "Macao",
    fr: "Macao",
    ja: "マカオ",
    pt: "Macau",
    zh: "Macau",
  },
  mp: {
    de: "Nördliche Marianen",
    en: "Northern Mariana Islands",
    es: "Islas Marianas del Norte",
    fr: "Îles Mariannes du Nord",
    ja: "北マリアナ諸島",
    pt: "Marianas Setentrionais",
    zh: "北马里亚纳群岛",
  },
  mq: {
    de: "Martinique",
    en: "Martinique",
    es: "Martinica",
    fr: "Martinique",
    ja: "マルティニーク",
    pt: "Martinica",
    zh: "马提尼克",
  },
  mr: {
    de: "Mauretanien",
    en: "Mauritania",
    es: "Mauritania",
    fr: "Mauritanie",
    ja: "モーリタニア",
    pt: "Mauritânia",
    zh: "毛里塔尼亚",
  },
  ms: {
    de: "Montserrat",
    en: "Montserrat",
    es: "Montserrat",
    fr: "Montserrat",
    ja: "モントセラト",
    pt: "Montserrat",
    zh: "蒙特塞拉特",
  },
  mt: {
    de: "Malta",
    en: "Malta",
    es: "Malta",
    fr: "Malte",
    ja: "マルタ",
    pt: "Malta",
    zh: "马耳他",
  },
  mu: {
    de: "Mauritius",
    en: "Mauritius",
    es: "Mauricio",
    fr: "Île Maurice",
    ja: "モーリシャス",
    pt: "Maurício",
    zh: "毛里求斯",
  },
  mv: {
    de: "Malediven",
    en: "Maldives",
    es: "Maldivas",
    fr: "Maldives",
    ja: "モルディブ",
    pt: "Maldivas",
    zh: "马尔代夫",
  },
  mw: {
    de: "Malawi",
    en: "Malawi",
    es: "Malawi",
    fr: "Malawi",
    ja: "マラウイ",
    pt: "Malawi",
    zh: "马拉维",
  },
  mx: {
    de: "Mexiko",
    en: "Mexico",
    es: "México",
    fr: "Mexique",
    ja: "メキシコ",
    pt: "México",
    zh: "墨西哥",
  },
  my: {
    de: "Malaysia",
    en: "Malaysia",
    es: "Malasia",
    fr: "Malaisie",
    ja: "マレーシア",
    pt: "Malásia",
    zh: "马来西亚",
  },
  mz: {
    de: "Mosambik",
    en: "Mozambique",
    es: "Mozambique",
    fr: "Mozambique",
    ja: "モザンビーク",
    pt: "Moçambique",
    zh: "莫桑比克",
  },
  na: {
    de: "Namibia",
    en: "Namibia",
    es: "Namibia",
    fr: "Namibie",
    ja: "ナミビア",
    pt: "Namíbia",
    zh: "纳米比亚",
  },
  nc: {
    de: "Neukaledonien",
    en: "New Caledonia",
    es: "Nueva Caledonia",
    fr: "Nouvelle-Calédonie",
    ja: "ニューカレドニア",
    pt: "Nova Caledónia",
    zh: "新喀里多尼亚",
  },
  ne: {
    de: "Niger",
    en: "Niger",
    es: "Níger",
    fr: "Niger",
    ja: "ニジェール",
    pt: "Níger",
    zh: "尼日尔",
  },
  nf: {
    de: "Norfolkinsel",
    en: "Norfolk Island",
    es: "Isla de Norfolk",
    fr: "Île Norfolk",
    ja: "ノーフォーク島",
    pt: "Ilha Norfolk",
    zh: "诺福克岛",
  },
  ng: {
    de: "Nigeria",
    en: "Nigeria",
    es: "Nigeria",
    fr: "Nigéria",
    ja: "ナイジェリア",
    pt: "Nigéria",
    zh: "尼日利亚",
  },
  ni: {
    de: "Nicaragua",
    en: "Nicaragua",
    es: "Nicaragua",
    fr: "Nicaragua",
    ja: "ニカラグア",
    pt: "Nicarágua",
    zh: "尼加拉瓜",
  },
  nl: {
    de: "Niederlande",
    en: "Netherlands",
    es: "Países Bajos",
    fr: "Pays-Bas",
    ja: "オランダ",
    pt: "Holanda",
    zh: "荷兰",
  },
  no: {
    de: "Norwegen",
    en: "Norway",
    es: "Noruega",
    fr: "Norvège",
    ja: "ノルウェー",
    pt: "Noruega",
    zh: "挪威",
  },
  np: {
    de: "Nepal",
    en: "Nepal",
    es: "Nepal",
    fr: "Népal",
    ja: "ネパール",
    pt: "Nepal",
    zh: "尼泊尔",
  },
  nr: {
    de: "Nauru",
    en: "Nauru",
    es: "Nauru",
    fr: "Nauru",
    ja: "ナウル",
    pt: "Nauru",
    zh: "瑙鲁",
  },
  nu: {
    de: "Niue",
    en: "Niue",
    es: "Niue",
    fr: "Niue",
    ja: "ニウエ",
    pt: "Niue",
    zh: "纽埃",
  },
  nz: {
    de: "Neuseeland",
    en: "New Zealand",
    es: "Nueva Zelanda",
    fr: "Nouvelle-Zélande",
    ja: "ニュージーランド",
    pt: "Nova Zelândia",
    zh: "新西兰",
  },
  om: {
    de: "Oman",
    en: "Oman",
    es: "Omán",
    fr: "Oman",
    ja: "オマーン",
    pt: "Omã",
    zh: "阿曼",
  },
  pa: {
    de: "Panama",
    en: "Panama",
    es: "Panamá",
    fr: "Panama",
    ja: "パナマ",
    pt: "Panamá",
    zh: "巴拿马",
  },
  pe: {
    de: "Peru",
    en: "Peru",
    es: "Perú",
    fr: "Pérou",
    ja: "ペルー",
    pt: "Perú",
    zh: "秘鲁",
  },
  pf: {
    de: "Französisch-Polynesien",
    en: "French Polynesia",
    es: "Polinesia Francesa",
    fr: "Polynésie française",
    ja: "フランス領ポリネシア",
    pt: "Polinésia Francesa",
    zh: "法属波利尼西亚",
  },
  pg: {
    de: "Papua-Neuguinea",
    en: "Papua New Guinea",
    es: "Papúa Nueva Guinea",
    fr: "Papouasie-Nouvelle-Guinée",
    ja: "パプアニューギニア",
    pt: "Papua Nova Guiné",
    zh: "巴布亚新几内亚",
  },
  ph: {
    de: "Philippinen",
    en: "Philippines",
    es: "Filipinas",
    fr: "Philippines",
    ja: "フィリピン",
    pt: "Filipinas",
    zh: "菲律宾",
  },
  pk: {
    de: "Pakistan",
    en: "Pakistan",
    es: "Pakistán",
    fr: "Pakistan",
    ja: "パキスタン",
    pt: "Paquistão",
    zh: "巴基斯坦",
  },
  pl: {
    de: "Polen",
    en: "Poland",
    es: "Polonia",
    fr: "Pologne",
    ja: "ポーランド",
    pt: "Polónia",
    zh: "波兰",
  },
  pm: {
    de: "St. Pierre und Miquelon",
    en: "Saint Pierre and Miquelon",
    es: "San Pedro y Miquelón",
    fr: "Saint-Pierre-et-Miquelon",
    ja: "サンピエール島・ミクロン島",
    pt: "Saint-Pierre e Miquelon",
    zh: "圣皮埃尔和密克隆",
  },
  pn: {
    de: "Pitcairninseln",
    en: "Pitcairn Islands",
    es: "Islas Pitcairn",
    fr: "Îles Pitcairn",
    ja: "ピトケアン",
    pt: "Ilhas Pitcairn",
    zh: "皮特凯恩群岛",
  },
  pr: {
    de: "Puerto Rico",
    en: "Puerto Rico",
    es: "Puerto Rico",
    fr: "Porto Rico",
    ja: "プエルトリコ",
    pt: "Porto Rico",
    zh: "波多黎各",
  },
  ps: {
    de: "Palästina",
    en: "Palestine",
    es: "Palestina",
    fr: "Palestine",
    ja: "パレスチナ",
    pt: "Palestina",
    zh: "巴勒斯坦",
  },
  pt: {
    de: "Portugal",
    en: "Portugal",
    es: "Portugal",
    fr: "Portugal",
    ja: "ポルトガル",
    pt: "Portugal",
    zh: "葡萄牙",
  },
  pw: {
    de: "Palau",
    en: "Palau",
    es: "Palau",
    fr: "Palaos (Palau)",
    ja: "パラオ",
    pt: "Palau",
    zh: "帕劳",
  },
  py: {
    de: "Paraguay",
    en: "Paraguay",
    es: "Paraguay",
    fr: "Paraguay",
    ja: "パラグアイ",
    pt: "Paraguai",
    zh: "巴拉圭",
  },
  qa: {
    de: "Katar",
    en: "Qatar",
    es: "Catar",
    fr: "Qatar",
    ja: "カタール",
    pt: "Catar",
    zh: "卡塔尔",
  },
  re: {
    de: "Réunion",
    en: "Réunion",
    es: "Reunión",
    fr: "Réunion",
    ja: "レユニオン",
    pt: "Reunião",
    zh: "留尼旺岛",
  },
  ro: {
    de: "Rumänien",
    en: "Romania",
    es: "Rumania",
    fr: "Roumanie",
    ja: "ルーマニア",
    pt: "Roménia",
    zh: "罗马尼亚",
  },
  rs: {
    de: "Serbien",
    en: "Serbia",
    es: "Serbia",
    fr: "Serbie",
    ja: "セルビア",
    pt: "Sérvia",
    zh: "塞尔维亚",
  },
  ru: {
    de: "Russland",
    en: "Russia",
    es: "Rusia",
    fr: "Russie",
    ja: "ロシア連邦",
    pt: "Rússia",
    zh: "俄罗斯",
  },
  rw: {
    de: "Ruanda",
    en: "Rwanda",
    es: "Ruanda",
    fr: "Rwanda",
    ja: "ルワンダ",
    pt: "Ruanda",
    zh: "卢旺达",
  },
  sa: {
    de: "Saudi-Arabien",
    en: "Saudi Arabia",
    es: "Arabia Saudí",
    fr: "Arabie Saoudite",
    ja: "サウジアラビア",
    pt: "Arábia Saudita",
    zh: "沙特阿拉伯",
  },
  sb: {
    de: "Salomonen",
    en: "Solomon Islands",
    es: "Islas Salomón",
    fr: "Îles Salomon",
    ja: "ソロモン諸島",
    pt: "Ilhas Salomão",
    zh: "所罗门群岛",
  },
  sc: {
    de: "Seychellen",
    en: "Seychelles",
    es: "Seychelles",
    fr: "Seychelles",
    ja: "セーシェル",
    pt: "Seicheles",
    zh: "塞舌尔",
  },
  sd: {
    de: "Sudan",
    en: "Sudan",
    es: "Sudán",
    fr: "Soudan",
    ja: "スーダン",
    pt: "Sudão",
    zh: "苏丹",
  },
  se: {
    de: "Schweden",
    en: "Sweden",
    es: "Suecia",
    fr: "Suède",
    ja: "スウェーデン",
    pt: "Suécia",
    zh: "瑞典",
  },
  sg: {
    de: "Singapur",
    en: "Singapore",
    es: "Singapur",
    fr: "Singapour",
    ja: "シンガポール",
    pt: "Singapura",
    zh: "Singapore",
  },
  sh: {
    de: "St. Helena, Ascension und Tristan da Cunha",
    en: "Saint Helena, Ascension and Tristan da Cunha",
    es: "Santa Elena, Ascensión y Tristán de Acuña",
    fr: "Sainte-Hélène, Ascension et Tristan da Cunha",
    ja: "セントヘレナ・アセンションおよびトリスタンダクーニャ",
    pt: "Santa Helena, Ascensão e Tristão da Cunha",
    zh: "圣赫勒拿、阿森松和特里斯坦-达库尼亚",
  },
  si: {
    de: "Slowenien",
    en: "Slovenia",
    es: "Eslovenia",
    fr: "Slovénie",
    ja: "スロベニア",
    pt: "Eslovénia",
    zh: "斯洛文尼亚",
  },
  sj: {
    de: "Spitzbergen und Jan Mayen",
    en: "Svalbard and Jan Mayen",
    es: "Islas Svalbard y Jan Mayen",
    fr: "Svalbard et Jan Mayen",
    ja: "スヴァールバル諸島およびヤンマイエン島",
    pt: "Ilhas Svalbard e Jan Mayen",
    zh: "斯瓦尔巴特",
  },
  sk: {
    de: "Slowakei",
    en: "Slovakia",
    es: "República Eslovaca",
    fr: "Slovaquie",
    ja: "スロバキア",
    pt: "Eslováquia",
    zh: "斯洛伐克",
  },
  sl: {
    de: "Sierra Leone",
    en: "Sierra Leone",
    es: "Sierra Leone",
    fr: "Sierra Leone",
    ja: "シエラレオネ",
    pt: "Serra Leoa",
    zh: "塞拉利昂",
  },
  sm: {
    de: "San Marino",
    en: "San Marino",
    es: "San Marino",
    fr: "Saint-Marin",
    ja: "サンマリノ",
    pt: "San Marino",
    zh: "圣马力诺",
  },
  sn: {
    de: "Senegal",
    en: "Senegal",
    es: "Senegal",
    fr: "Sénégal",
    ja: "セネガル",
    pt: "Senegal",
    zh: "塞内加尔",
  },
  so: {
    de: "Somalia",
    en: "Somalia",
    es: "Somalia",
    fr: "Somalie",
    ja: "ソマリア",
    pt: "Somália",
    zh: "索马里",
  },
  sr: {
    de: "Suriname",
    en: "Suriname",
    es: "Surinam",
    fr: "Surinam",
    ja: "スリナム",
    pt: "Suriname",
    zh: "苏里南",
  },
  ss: {
    de: "Südsudan",
    en: "South Sudan",
    es: "Sudán del Sur",
    fr: "Soudan du Sud",
    ja: "南スーダン",
    pt: "Sudão do Sul",
    zh: "南苏丹",
  },
  st: {
    de: "São Tomé und Príncipe",
    en: "São Tomé and Príncipe",
    es: "Santo Tomé y Príncipe",
    fr: "São Tomé et Príncipe",
    ja: "サントメ・プリンシペ",
    pt: "São Tomé e Príncipe",
    zh: "圣多美和普林西比",
  },
  sv: {
    de: "El Salvador",
    en: "El Salvador",
    es: "El Salvador",
    fr: "Salvador",
    ja: "エルサルバドル",
    pt: "El Salvador",
    zh: "萨尔瓦多",
  },
  sx: {
    de: "Sint Maarten",
    en: "Sint Maarten",
    es: "Sint Maarten",
    fr: "Saint-Martin",
    ja: "シント・マールテン",
    pt: "São Martinho",
    zh: "圣马丁岛",
  },
  sy: {
    de: "Syrien",
    en: "Syria",
    es: "Siria",
    fr: "Syrie",
    ja: "シリア・アラブ共和国",
    pt: "Síria",
    zh: "叙利亚",
  },
  sz: {
    de: "Swasiland",
    en: "Eswatini",
    es: "Suazilandia",
    fr: "Swaziland",
    ja: "スワジランド",
    pt: "Suazilândia",
    zh: "斯威士兰",
  },
  tc: {
    de: "Turks-und Caicosinseln",
    en: "Turks and Caicos Islands",
    es: "Islas Turks y Caicos",
    fr: "Îles Turques-et-Caïques",
    ja: "タークス・カイコス諸島",
    pt: "Ilhas Turks e Caicos",
    zh: "特克斯和凯科斯群岛",
  },
  td: {
    de: "Tschad",
    en: "Chad",
    es: "Chad",
    fr: "Tchad",
    ja: "チャド",
    pt: "Chade",
    zh: "乍得",
  },
  tf: {
    de: "Französische Süd- und Antarktisgebiete",
    en: "French Southern and Antarctic Lands",
    es: "Tierras Australes y Antárticas Francesas",
    fr: "Terres australes et antarctiques françaises",
    ja: "フランス領南方・南極地域",
    pt: "Terras Austrais e Antárticas Francesas",
    zh: "法国南部和南极土地",
  },
  tg: {
    de: "Togo",
    en: "Togo",
    es: "Togo",
    fr: "Togo",
    ja: "トーゴ",
    pt: "Togo",
    zh: "多哥",
  },
  th: {
    de: "Thailand",
    en: "Thailand",
    es: "Tailandia",
    fr: "Thaïlande",
    ja: "タイ",
    pt: "Tailândia",
    zh: "泰国",
  },
  tj: {
    de: "Tadschikistan",
    en: "Tajikistan",
    es: "Tayikistán",
    fr: "Tadjikistan",
    ja: "タジキスタン",
    pt: "Tajiquistão",
    zh: "塔吉克斯坦",
  },
  tk: {
    de: "Tokelau",
    en: "Tokelau",
    es: "Islas Tokelau",
    fr: "Tokelau",
    ja: "トケラウ",
    pt: "Tokelau",
    zh: "托克劳",
  },
  tl: {
    de: "Osttimor",
    en: "Timor-Leste",
    es: "Timor Oriental",
    fr: "Timor oriental",
    ja: "東ティモール",
    pt: "Timor-Leste",
    zh: "东帝汶",
  },
  tm: {
    de: "Turkmenistan",
    en: "Turkmenistan",
    es: "Turkmenistán",
    fr: "Turkménistan",
    ja: "トルクメニスタン",
    pt: "Turquemenistão",
    zh: "土库曼斯坦",
  },
  tn: {
    de: "Tunesien",
    en: "Tunisia",
    es: "Túnez",
    fr: "Tunisie",
    ja: "チュニジア",
    pt: "Tunísia",
    zh: "突尼斯",
  },
  to: {
    de: "Tonga",
    en: "Tonga",
    es: "Tonga",
    fr: "Tonga",
    ja: "トンガ",
    pt: "Tonga",
    zh: "汤加",
  },
  tr: {
    de: "Türkei",
    en: "Turkey",
    es: "Turquía",
    fr: "Turquie",
    ja: "トルコ",
    pt: "Turquia",
    zh: "土耳其",
  },
  tt: {
    de: "Trinidad und Tobago",
    en: "Trinidad and Tobago",
    es: "Trinidad y Tobago",
    fr: "Trinité-et-Tobago",
    ja: "トリニダード・トバゴ",
    pt: "Trinidade e Tobago",
    zh: "特立尼达和多巴哥",
  },
  tv: {
    de: "Tuvalu",
    en: "Tuvalu",
    es: "Tuvalu",
    fr: "Tuvalu",
    ja: "ツバル",
    pt: "Tuvalu",
    zh: "图瓦卢",
  },
  tw: {
    de: "Taiwan",
    en: "Taiwan",
    es: "Taiwán",
    fr: "Taïwan",
    ja: "台湾",
    pt: "Ilha Formosa",
    zh: "Taiwan",
  },
  tz: {
    de: "Tansania",
    en: "Tanzania",
    es: "Tanzania",
    fr: "Tanzanie",
    ja: "タンザニア",
    pt: "Tanzânia",
    zh: "坦桑尼亚",
  },
  ua: {
    de: "Ukraine",
    en: "Ukraine",
    es: "Ucrania",
    fr: "Ukraine",
    ja: "ウクライナ",
    pt: "Ucrânia",
    zh: "乌克兰",
  },
  ug: {
    de: "Uganda",
    en: "Uganda",
    es: "Uganda",
    fr: "Ouganda",
    ja: "ウガンダ",
    pt: "Uganda",
    zh: "乌干达",
  },
  um: {
    de: "Kleinere Inselbesitzungen der Vereinigten Staaten",
    en: "United States Minor Outlying Islands",
    es: "Islas Ultramarinas Menores de Estados Unidos",
    fr: "Îles mineures éloignées des États-Unis",
    ja: "合衆国領有小離島",
    pt: "Ilhas Menores Distantes dos Estados Unidos",
    zh: "美国本土外小岛屿",
  },
  us: {
    de: "Vereinigte Staaten",
    en: "United States",
    es: "Estados Unidos",
    fr: "États-Unis",
    ja: "アメリカ合衆国",
    pt: "Estados Unidos",
    zh: "美国",
  },
  uy: {
    de: "Uruguay",
    en: "Uruguay",
    es: "Uruguay",
    fr: "Uruguay",
    ja: "ウルグアイ",
    pt: "Uruguai",
    zh: "乌拉圭",
  },
  uz: {
    de: "Usbekistan",
    en: "Uzbekistan",
    es: "Uzbekistán",
    fr: "Ouzbékistan",
    ja: "ウズベキスタン",
    pt: "Uzbequistão",
    zh: "乌兹别克斯坦",
  },
  va: {
    de: "Vatikanstadt",
    en: "Vatican City",
    es: "Ciudad del Vaticano",
    fr: "Cité du Vatican",
    ja: "バチカン市国",
    pt: "Cidade do Vaticano",
    zh: "梵蒂冈",
  },
  vc: {
    de: "St. Vincent und die Grenadinen",
    en: "Saint Vincent and the Grenadines",
    es: "San Vicente y Granadinas",
    fr: "Saint-Vincent-et-les-Grenadines",
    ja: "セントビンセントおよびグレナディーン諸島",
    pt: "São Vincente e Granadinas",
    zh: "圣文森特和格林纳丁斯",
  },
  ve: {
    de: "Venezuela",
    en: "Venezuela",
    es: "Venezuela",
    fr: "Venezuela",
    ja: "ベネズエラ・ボリバル共和国",
    pt: "Venezuela",
    zh: "委内瑞拉",
  },
  vg: {
    de: "Britische Jungferninseln",
    en: "British Virgin Islands",
    es: "Islas Vírgenes del Reino Unido",
    fr: "Îles Vierges britanniques",
    ja: "イギリス領ヴァージン諸島",
    pt: "Ilhas Virgens",
    zh: "英属维尔京群岛",
  },
  vi: {
    de: "Amerikanische Jungferninseln",
    en: "United States Virgin Islands",
    es: "Islas Vírgenes de los Estados Unidos",
    fr: "Îles Vierges des États-Unis",
    ja: "アメリカ領ヴァージン諸島",
    pt: "Ilhas Virgens dos Estados Unidos",
    zh: "美属维尔京群岛",
  },
  vn: {
    de: "Vietnam",
    en: "Vietnam",
    es: "Vietnam",
    fr: "Viêt Nam",
    ja: "ベトナム",
    pt: "Vietname",
    zh: "越南",
  },
  vu: {
    de: "Vanuatu",
    en: "Vanuatu",
    es: "Vanuatu",
    fr: "Vanuatu",
    ja: "バヌアツ",
    pt: "Vanuatu",
    zh: "瓦努阿图",
  },
  wf: {
    de: "Wallis und Futuna",
    en: "Wallis and Futuna",
    es: "Wallis y Futuna",
    fr: "Wallis-et-Futuna",
    ja: "ウォリス・フツナ",
    pt: "Wallis e Futuna",
    zh: "瓦利斯和富图纳群岛",
  },
  ws: {
    de: "Samoa",
    en: "Samoa",
    es: "Samoa",
    fr: "Samoa",
    ja: "サモア",
    pt: "Samoa",
    zh: "萨摩亚",
  },
  xk: {
    de: "Kosovo",
    en: "Kosovo",
    es: "Kosovo",
    fr: "Kosovo",
    ja: "Kosovo",
    pt: "Kosovo",
    zh: "科索沃",
  },
  ye: {
    de: "Jemen",
    en: "Yemen",
    es: "Yemen",
    fr: "Yémen",
    ja: "イエメン",
    pt: "Iémen",
    zh: "也门",
  },
  yt: {
    de: "Mayotte",
    en: "Mayotte",
    es: "Mayotte",
    fr: "Mayotte",
    ja: "マヨット",
    pt: "Mayotte",
    zh: "马约特",
  },
  za: {
    de: "Südafrika",
    en: "South Africa",
    es: "Sudáfrica",
    fr: "Afrique du Sud",
    ja: "南アフリカ",
    pt: "África do Sul",
    zh: "南非",
  },
  zm: {
    de: "Sambia",
    en: "Zambia",
    es: "Zambia",
    fr: "Zambie",
    ja: "ザンビア",
    pt: "Zâmbia",
    zh: "赞比亚",
  },
  zw: {
    de: "Simbabwe",
    en: "Zimbabwe",
    es: "Zimbabue",
    fr: "Zimbabwe",
    ja: "ジンバブエ",
    pt: "Zimbabwe",
    zh: "津巴布韦",
  },
} as const;

export default countryNames;
